/**
 * Triggers DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Triggers Domain Module - Composition root
 *
 * DDD: Composition root for triggers domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  FireRepositoryAdapter,
  SmartContractTriggerRepositoryAdapter,
} from "@ledgerfit/adapters/triggers";
import { getIdGeneratorService } from "@ledgerfit/adapters";
import type { AdapterDynamoDBClient } from "@ledgerfit/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateSmartContractTrigger,
  ExecuteFireSmartContractTrigger,
  ExecuteGetSmartContractTrigger,
  ExecuteListSmartContractTriggers,
  ExecuteUpdateSmartContractTrigger,
} from "@ledgerfit/services/triggers/usecases";
// Ports (interfaces)
import type {
  FireRepository,
  SmartContractTriggerRepository,
} from "@ledgerfit/services/triggers/ports";

export interface TriggersDomainModule {
  repos: {
    fires: FireRepository;
    smartContractTriggers: SmartContractTriggerRepository;
  };
  useCases: {
    fires: {
      get: ExecuteFireSmartContractTrigger;
    };
    smartContractTriggers: {
      create: ExecuteCreateSmartContractTrigger;
      get: ExecuteGetSmartContractTrigger;
      list: ExecuteListSmartContractTriggers;
      update: ExecuteUpdateSmartContractTrigger;
    };
  };
}

export function buildTriggersDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): TriggersDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      fires?: FireRepository;
      smartContractTriggers?: SmartContractTriggerRepository;
    } = {};

    obj.fires = new FireRepositoryAdapter(dynamoClient);
    obj.smartContractTriggers = new SmartContractTriggerRepositoryAdapter(dynamoClient);
    return {
      fires: obj.fires!,
      smartContractTriggers: obj.smartContractTriggers!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    fires: {
      get: new ExecuteFireSmartContractTrigger(executionContext, idGenerator, repos.fires),
    },
    smartContractTriggers: {
      create: new ExecuteCreateSmartContractTrigger(executionContext, idGenerator, repos.smartContractTriggers),
      get: new ExecuteGetSmartContractTrigger(executionContext, idGenerator, repos.smartContractTriggers),
      list: new ExecuteListSmartContractTriggers(executionContext, idGenerator, repos.smartContractTriggers),
      update: new ExecuteUpdateSmartContractTrigger(executionContext, idGenerator, repos.smartContractTriggers),
    },
  };
  return { repos, useCases: useCases as TriggersDomainModule["useCases"] };
}
