/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Ledgers Domain Use Cases
 * 
 * List of all use case names for the ledgers domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const LEDGERS_USE_CASES = [
  "executeAcknowledgeFreezeOrder",
  "executeAddPharmacyMember",
  "executeAnchorPrescriptionEvent",
  "executeFreezePharmacyMember",
  "executeGetLedger",
  "executeListFreezeOrders",
  "executeListLedgers",
  "executeListPharmacyMembers",
  "executeListPrescriptionEventRefs",
  "executeRegisterLedger",
  "executeReleaseFreezeOrder"
] as const;
