/**
 * Investigation DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Investigation Domain Module - Composition root
 *
 * DDD: Composition root for investigation domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  CaseNoteRepositoryAdapter,
  DecideRepositoryAdapter,
  HitRepositoryAdapter,
  RevealRepositoryAdapter,
} from "@ledgerfit/adapters/investigation";
import { getIdGeneratorService } from "@ledgerfit/adapters";
import type { AdapterDynamoDBClient } from "@ledgerfit/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteCreateCaseNote,
  ExecuteCreateRevealRequest,
  ExecuteDecideRevealRequest,
  ExecuteGetRevealRequest,
  ExecuteListCaseNotes,
  ExecuteListMaskedHits,
  ExecuteListRevealRequests,
} from "@ledgerfit/services/investigation/usecases";
// Ports (interfaces)
import type {
  CaseNoteRepository,
  DecideRepository,
  HitRepository,
  RevealRepository,
} from "@ledgerfit/services/investigation/ports";

export interface InvestigationDomainModule {
  repos: {
    caseNotes: CaseNoteRepository;
    decides: DecideRepository;
    hits: HitRepository;
    reveals: RevealRepository;
  };
  useCases: {
    caseNotes: {
      create: ExecuteCreateCaseNote;
      list: ExecuteListCaseNotes;
    };
    decides: {
      get: ExecuteDecideRevealRequest;
    };
    hits: {
      list: ExecuteListMaskedHits;
    };
    reveals: {
      create: ExecuteCreateRevealRequest;
      get: ExecuteGetRevealRequest;
      list: ExecuteListRevealRequests;
    };
  };
}

export function buildInvestigationDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): InvestigationDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      caseNotes?: CaseNoteRepository;
      decides?: DecideRepository;
      hits?: HitRepository;
      reveals?: RevealRepository;
    } = {};

    obj.caseNotes = new CaseNoteRepositoryAdapter(dynamoClient);
    obj.decides = new DecideRepositoryAdapter(dynamoClient);
    obj.hits = new HitRepositoryAdapter(dynamoClient);
    obj.reveals = new RevealRepositoryAdapter(dynamoClient);
    return {
      caseNotes: obj.caseNotes!,
      decides: obj.decides!,
      hits: obj.hits!,
      reveals: obj.reveals!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    caseNotes: {
      create: new ExecuteCreateCaseNote(executionContext, idGenerator, repos.caseNotes),
      list: new ExecuteListCaseNotes(executionContext, idGenerator, repos.caseNotes),
    },
    decides: {
      get: new ExecuteDecideRevealRequest(executionContext, idGenerator, repos.decides),
    },
    hits: {
      list: new ExecuteListMaskedHits(executionContext, idGenerator, repos.hits),
    },
    reveals: {
      create: new ExecuteCreateRevealRequest(executionContext, idGenerator, repos.reveals),
      get: new ExecuteGetRevealRequest(executionContext, idGenerator, repos.reveals),
      list: new ExecuteListRevealRequests(executionContext, idGenerator, repos.reveals),
    },
  };
  return { repos, useCases: useCases as InvestigationDomainModule["useCases"] };
}
