/**
 * GetRevealRequest handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getRevealRequest } from "@ledgerfit/api-server/domains/investigation/handlers";
import type { InvestigationDDDDependencies } from "@ledgerfit/api-server/domains/investigation";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { INVESTIGATION_USE_CASES } from "../__factories__/use-cases.js";

describe("GetRevealRequest", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: InvestigationDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<InvestigationDDDDependencies>(
      INVESTIGATION_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetRevealRequest, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { revealRequestId: entity.id };

    await getRevealRequest(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetRevealRequest.execute).toHaveBeenCalledWith(expect.objectContaining({ revealRequestId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { revealRequestId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetRevealRequest, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getRevealRequest(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
