/**
 * Export DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Export DTOs
 *
 * DDD: Application DTOs for Export use cases.
 */

import type { ExportProvenanceAuditPackRequestInput } from "@ledgerfit/core/provenance/types";

export type ExportProvenanceAuditPackInput = ExportProvenanceAuditPackRequestInput;

export type ExportProvenanceAuditPackOutput = {};
