/**
 * EventRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * EventRepository Port
 *
 * DDD: Application port for eventrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AnchorPrescriptionEventInput, AnchorPrescriptionEventOutput, ListPrescriptionEventRefsInput, ListPrescriptionEventRefsOutput } from "../dto/event.dto";
export interface EventRepository {
  listPrescriptionEventRefs(input: ListPrescriptionEventRefsInput): Promise<ListPrescriptionEventRefsOutput>;
  anchorPrescriptionEvent(input: AnchorPrescriptionEventInput): Promise<AnchorPrescriptionEventOutput>;
}

export type { AnchorPrescriptionEventInput, AnchorPrescriptionEventOutput, ListPrescriptionEventRefsInput, ListPrescriptionEventRefsOutput } from "../dto/event.dto";
