/**
 * LedgerRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LedgerRepository Port
 *
 * DDD: Application port for ledgerrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { GetLedgerInput, GetLedgerOutput, ListLedgersInput, ListLedgersOutput, RegisterLedgerInput, RegisterLedgerOutput } from "../dto/ledger.dto";
export interface LedgerRepository {
  listLedgers(input: ListLedgersInput): Promise<ListLedgersOutput>;
  registerLedger(input: RegisterLedgerInput): Promise<RegisterLedgerOutput>;
  getLedger(input: GetLedgerInput): Promise<GetLedgerOutput>;
}

export type { GetLedgerInput, GetLedgerOutput, ListLedgersInput, ListLedgersOutput, RegisterLedgerInput, RegisterLedgerOutput } from "../dto/ledger.dto";
