/**
 * MemberRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * MemberRepository Port
 *
 * DDD: Application port for memberrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { AddPharmacyMemberInput, AddPharmacyMemberOutput, ListPharmacyMembersInput, ListPharmacyMembersOutput } from "../dto/member.dto";
export interface MemberRepository {
  listPharmacyMembers(input: ListPharmacyMembersInput): Promise<ListPharmacyMembersOutput>;
  addPharmacyMember(input: AddPharmacyMemberInput): Promise<AddPharmacyMemberOutput>;
}

export type { AddPharmacyMemberInput, AddPharmacyMemberOutput, ListPharmacyMembersInput, ListPharmacyMembersOutput } from "../dto/member.dto";
