/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { fireRoutes } from "./fire.routes.js";
export { smartContractTriggerRoutes } from "./smart-contract-trigger.routes.js";
