/**
 * Routes for SmartContractTrigger
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createSmartContractTrigger, getSmartContractTrigger, listSmartContractTriggers, updateSmartContractTrigger } from "../handlers/smart-contract-trigger.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function smartContractTriggerRoutes(fastify: FastifyInstance) {
  // POST /v1/smart-contract-triggers (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/smart-contract-triggers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTriggersDependenciesForRequest();
        await createSmartContractTrigger(request, reply, deps);
      });
    }
  );


  // GET /v1/smart-contract-triggers (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/smart-contract-triggers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTriggersDependenciesForRequest();
        await listSmartContractTriggers(request, reply, deps);
      });
    }
  );


  // GET /v1/smart-contract-triggers/{triggerId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/smart-contract-triggers/:triggerId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { triggerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTriggersDependenciesForRequest();
        await getSmartContractTrigger(request, reply, deps);
      });
    }
  );


  // PATCH /v1/smart-contract-triggers/{triggerId} (unscoped; scope set for security middleware)
  fastify.patch(
    "/v1/smart-contract-triggers/:triggerId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { triggerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getTriggersDependenciesForRequest();
        await updateSmartContractTrigger(request, reply, deps);
      });
    }
  );


}
