/**
 * Handlers for TrainingJob
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TrainingDomainModule } from "../dependencies/training-ddd.dependencies.js";
import type { CreateTrainingJobInput, GetTrainingJobInput, ListTrainingJobsInput } from "@ledgerfit/services/training";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/training-jobs
 * Operation: listTrainingJobs
 */
export async function listTrainingJobs(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: TrainingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListTrainingJobsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.jobs.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/training-jobs
 * Operation: createTrainingJob
 */
export async function createTrainingJob(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TrainingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateTrainingJobInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.jobs.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/training-jobs/{jobId}
 * Operation: getTrainingJob
 */
export async function getTrainingJob(
  request: FastifyRequest<{ Params: { jobId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TrainingDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetTrainingJobInput = {
    jobId: request.params.jobId,
  };
  const result = await deps.useCases.jobs.get.execute(input);
  return reply.code(200).send(result);
}


