/**
 * Models DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Models Domain Module - Composition root
 *
 * DDD: Composition root for models domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ModelArtefactRepositoryAdapter,
  PromoteRepositoryAdapter,
  RuleRepositoryAdapter,
} from "@ledgerfit/adapters/models";
import { getIdGeneratorService } from "@ledgerfit/adapters";
import type { AdapterDynamoDBClient } from "@ledgerfit/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteGetModelArtefact,
  ExecuteListAssociationRules,
  ExecuteListModelArtefacts,
  ExecutePromoteModelArtefact,
  ExecuteRegisterModelArtefact,
} from "@ledgerfit/services/models/usecases";
// Ports (interfaces)
import type {
  ModelArtefactRepository,
  PromoteRepository,
  RuleRepository,
} from "@ledgerfit/services/models/ports";

export interface ModelsDomainModule {
  repos: {
    modelArtefacts: ModelArtefactRepository;
    promotes: PromoteRepository;
    rules: RuleRepository;
  };
  useCases: {
    modelArtefacts: {
      create: ExecuteRegisterModelArtefact;
      get: ExecuteGetModelArtefact;
      list: ExecuteListModelArtefacts;
    };
    promotes: {
      get: ExecutePromoteModelArtefact;
    };
    rules: {
      list: ExecuteListAssociationRules;
    };
  };
}

export function buildModelsDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): ModelsDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      modelArtefacts?: ModelArtefactRepository;
      promotes?: PromoteRepository;
      rules?: RuleRepository;
    } = {};

    obj.modelArtefacts = new ModelArtefactRepositoryAdapter(dynamoClient);
    obj.promotes = new PromoteRepositoryAdapter(dynamoClient);
    obj.rules = new RuleRepositoryAdapter(dynamoClient);
    return {
      modelArtefacts: obj.modelArtefacts!,
      promotes: obj.promotes!,
      rules: obj.rules!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    modelArtefacts: {
      create: new ExecuteRegisterModelArtefact(executionContext, idGenerator, repos.modelArtefacts),
      get: new ExecuteGetModelArtefact(executionContext, idGenerator, repos.modelArtefacts),
      list: new ExecuteListModelArtefacts(executionContext, idGenerator, repos.modelArtefacts),
    },
    promotes: {
      get: new ExecutePromoteModelArtefact(executionContext, idGenerator, repos.promotes),
    },
    rules: {
      list: new ExecuteListAssociationRules(executionContext, idGenerator, repos.rules),
    },
  };
  return { repos, useCases: useCases as ModelsDomainModule["useCases"] };
}
