/**
 * TrainingJob Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { TrainingJobEntity } from "@ledgerfit/core/training/models/index.js";
import { trainingSchemas } from "@ledgerfit/core/training";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "trn";

export function createTrainingJob(overrides: Partial<TrainingJobEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    executionMode: overrides.executionMode ?? "serverBatch",
    ledgerId: overrides.ledgerId ?? faker.string.uuid(),
    lifecycleStep: overrides.lifecycleStep ?? "modelInitialization",
    status: overrides.status ?? "queued",
    ...overrides,
  };

  return trainingSchemas.TrainingJob.parse(raw);
}

export function trainingJobBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createTrainingJob(overrides));
}
