/**
 * TrainingJob Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/training.openapi.types.js";
import { schemas } from "../schemas/training.schemas.js";

/**
 * Entity: TrainingJobEntity
 * Description: Represents the TrainingJob domain model.
 * Source: schemas.TrainingJob
 * Type: Domain Entity (API)
 */
export const TrainingJobEntitySchema = schemas.TrainingJob;
export type TrainingJobEntity = components["schemas"]["TrainingJob"];
