/**
 * FreezeOrder Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/ledgers.openapi.types.js";
import { schemas } from "../schemas/ledgers.schemas.js";

/**
 * Entity: FreezeOrderEntity
 * Description: Represents the FreezeOrder domain model.
 * Source: schemas.FreezeOrder
 * Type: Domain Entity (API)
 */
export const FreezeOrderEntitySchema = schemas.FreezeOrder;
export type FreezeOrderEntity = components["schemas"]["FreezeOrder"];
