/**
 * SmartContractTriggerRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SmartContractTriggerRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements SmartContractTriggerRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  SmartContractTriggerRepository,
} from "@ledgerfit/services/triggers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { SmartContractTriggerRepositoryDdb } from "./smart-contract-trigger-repository.ddb.js";

/**
 * SmartContractTriggerRepositoryAdapter
 *
 * Implements SmartContractTriggerRepository port for infrastructure layer.
 */
export class SmartContractTriggerRepositoryAdapter implements SmartContractTriggerRepository {
  private readonly ddb: SmartContractTriggerRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new SmartContractTriggerRepositoryDdb(this.dynamoClient);
  }

  async listSmartContractTriggers(input: Parameters<SmartContractTriggerRepository['listSmartContractTriggers']>[0]): Promise<Awaited<ReturnType<SmartContractTriggerRepository['listSmartContractTriggers']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listSmartContractTriggers(input);
  }

  async createSmartContractTrigger(input: Parameters<SmartContractTriggerRepository['createSmartContractTrigger']>[0]): Promise<Awaited<ReturnType<SmartContractTriggerRepository['createSmartContractTrigger']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createSmartContractTrigger(input);
  }

  async getSmartContractTrigger(input: Parameters<SmartContractTriggerRepository['getSmartContractTrigger']>[0]): Promise<Awaited<ReturnType<SmartContractTriggerRepository['getSmartContractTrigger']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getSmartContractTrigger(input);
  }

  async updateSmartContractTrigger(input: Parameters<SmartContractTriggerRepository['updateSmartContractTrigger']>[0]): Promise<Awaited<ReturnType<SmartContractTriggerRepository['updateSmartContractTrigger']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.updateSmartContractTrigger(input);
  }
}
