/**
 * Repository interface for DataSourcePolicy
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  DataSourcePolicyEntity
} from "../models/data-source-policy.entity.js";
import type {
  ListDataSourcePoliciesParams,
  DataSourcePolicy
} from "../types/index.js";
/**
 * DataSourcePolicyRepository Interface
 */
export interface DataSourcePolicyRepository extends CreateReadRepository<DataSourcePolicyEntity, DataSourcePolicy, string, ListDataSourcePoliciesParams> {

}
