/**
 * GetTrainingJob handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getTrainingJob } from "@ledgerfit/api-server/domains/training/handlers";
import type { TrainingDDDDependencies } from "@ledgerfit/api-server/domains/training";
import { createTrainingJob as createTrainingJobEntity } from "@ledgerfit/factories/training";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { TRAINING_USE_CASES } from "../__factories__/use-cases.js";

describe("GetTrainingJob", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TrainingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TrainingDDDDependencies>(
      TRAINING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createTrainingJobEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetTrainingJob, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { jobId: entity.id };

    await getTrainingJob(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetTrainingJob.execute).toHaveBeenCalledWith(expect.objectContaining({ jobId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { jobId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetTrainingJob, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getTrainingJob(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
