/**
 * ListTrainingJobs handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listTrainingJobs } from "@ledgerfit/api-server/domains/training/handlers";
import type { TrainingDDDDependencies } from "@ledgerfit/api-server/domains/training";
import { createTrainingJob as createTrainingJobEntity } from "@ledgerfit/factories/training";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { TRAINING_USE_CASES } from "../__factories__/use-cases.js";

describe("ListTrainingJobs", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TrainingDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TrainingDDDDependencies>(
      TRAINING_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createTrainingJobEntity({ orgId }),
      createTrainingJobEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListTrainingJobs, "execute").mockResolvedValue(useCaseResult);

    await listTrainingJobs(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListTrainingJobs.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
