/**
 * ModelArtefact DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ModelArtefact DTOs
 *
 * DDD: Application DTOs for ModelArtefact use cases.
 */

import type { GetModelArtefactParams, ListModelArtefactsParams, RegisterModelArtefactRequestInput } from "@ledgerfit/core/models/types";

export type ListModelArtefactsInput = ListModelArtefactsParams;

export type RegisterModelArtefactInput = RegisterModelArtefactRequestInput;

export type GetModelArtefactInput = GetModelArtefactParams;

export type ListModelArtefactsOutput = {};

export type RegisterModelArtefactOutput = {};

export type GetModelArtefactOutput = {};
