/**
 * ExecuteExportProvenanceAuditPack - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteExportProvenanceAuditPack Use Case
 *
 * DDD: Application use case for list Export.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ExportProvenanceAuditPackInput, ExportProvenanceAuditPackOutput } from "../dto/export.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { ExportRepository } from "../ports";

export class ExecuteExportProvenanceAuditPack {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly exportRepo: ExportRepository
  ) {}

  async execute(input: ExportProvenanceAuditPackInput): Promise<ExportProvenanceAuditPackOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.prvId();

    // All field names extracted from OpenAPI spec: artefactIds, includePhi, note
    // List entities via repository
    const result = await this.exportRepo.exportProvenanceAuditPack({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ExportProvenanceAuditPackOutput;
  }
}
