/**
 * AcknowledgeRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * AcknowledgeRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements AcknowledgeRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  AcknowledgeRepository,
} from "@ledgerfit/services/ledgers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { AcknowledgeRepositoryDdb } from "./acknowledge-repository.ddb.js";

/**
 * AcknowledgeRepositoryAdapter
 *
 * Implements AcknowledgeRepository port for infrastructure layer.
 */
export class AcknowledgeRepositoryAdapter implements AcknowledgeRepository {
  private readonly ddb: AcknowledgeRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new AcknowledgeRepositoryDdb(this.dynamoClient);
  }

  async acknowledgeFreezeOrder(input: Parameters<AcknowledgeRepository['acknowledgeFreezeOrder']>[0]): Promise<Awaited<ReturnType<AcknowledgeRepository['acknowledgeFreezeOrder']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.acknowledgeFreezeOrder(input);
  }
}
