/**
 * FreezeOrderRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * FreezeOrderRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements FreezeOrderRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  FreezeOrderRepository,
} from "@ledgerfit/services/ledgers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { FreezeOrderRepositoryDdb } from "./freeze-order-repository.ddb.js";

/**
 * FreezeOrderRepositoryAdapter
 *
 * Implements FreezeOrderRepository port for infrastructure layer.
 */
export class FreezeOrderRepositoryAdapter implements FreezeOrderRepository {
  private readonly ddb: FreezeOrderRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new FreezeOrderRepositoryDdb(this.dynamoClient);
  }

  async listFreezeOrders(input: Parameters<FreezeOrderRepository['listFreezeOrders']>[0]): Promise<Awaited<ReturnType<FreezeOrderRepository['listFreezeOrders']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listFreezeOrders(input);
  }
}
