/**
 * LedgerRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * LedgerRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements LedgerRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  LedgerRepository,
} from "@ledgerfit/services/ledgers";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { LedgerRepositoryDdb } from "./ledger-repository.ddb.js";

/**
 * LedgerRepositoryAdapter
 *
 * Implements LedgerRepository port for infrastructure layer.
 */
export class LedgerRepositoryAdapter implements LedgerRepository {
  private readonly ddb: LedgerRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new LedgerRepositoryDdb(this.dynamoClient);
  }

  async listLedgers(input: Parameters<LedgerRepository['listLedgers']>[0]): Promise<Awaited<ReturnType<LedgerRepository['listLedgers']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listLedgers(input);
  }

  async registerLedger(input: Parameters<LedgerRepository['registerLedger']>[0]): Promise<Awaited<ReturnType<LedgerRepository['registerLedger']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerLedger(input);
  }

  async getLedger(input: Parameters<LedgerRepository['getLedger']>[0]): Promise<Awaited<ReturnType<LedgerRepository['getLedger']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getLedger(input);
  }
}
