/**
 * Domain routes – register all domain route modules.
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Rescans platform/api-server/src/domains and includes only domains that have
 * routes/index.ts and dependencies/{domain}-ddd.dependencies.ts.
 * Extension excludes/imports from x-codegen.api-server.extensions in OpenAPI YAML.
 */

import type { FastifyInstance } from "fastify";
import { registerDomainFromModule } from "./route-registration.js";

// Static imports so the bundle includes all domain route modules
import * as governanceRoutes from "../../domains/governance/routes/index.js";
import * as identityRoutes from "../../domains/identity/routes/index.js";
import * as investigationRoutes from "../../domains/investigation/routes/index.js";
import * as ledgersRoutes from "../../domains/ledgers/routes/index.js";
import * as modelsRoutes from "../../domains/models/routes/index.js";
import * as provenanceRoutes from "../../domains/provenance/routes/index.js";
import * as trainingRoutes from "../../domains/training/routes/index.js";
import * as triggersRoutes from "../../domains/triggers/routes/index.js";

const DOMAIN_MODULES: Array<{
  domain: string;
  mod: Record<string, unknown>;
  exclude?: string[];
}> = [
  { domain: "governance", mod: governanceRoutes },
  {
    domain: "identity", mod: identityRoutes,
    exclude: ["authRoutes", "loginRoutes", "logoutRoutes", "signupRoutes", "sessionRoutes", "refreshRoutes", "tokenRoutes", "profileRoutes"],
  },
  { domain: "investigation", mod: investigationRoutes },
  { domain: "ledgers", mod: ledgersRoutes },
  { domain: "models", mod: modelsRoutes },
  { domain: "provenance", mod: provenanceRoutes },
  { domain: "training", mod: trainingRoutes },
  { domain: "triggers", mod: triggersRoutes },
];

export async function registerAllDomainRoutes(
  fastify: FastifyInstance,
): Promise<void> {
  console.log("[DEBUG] Registering domain routes...");
  try {
    for (const { domain, mod, exclude } of DOMAIN_MODULES) {
      await registerDomainFromModule(fastify, domain, mod, exclude ?? []);
    }
    console.log("[DEBUG] ✅ All domain routes registered");
  } catch (error: unknown) {
    const err = error instanceof Error ? error : new Error(String(error));
    console.error("[DEBUG] ❌ Error registering domain routes:", err.message);
    if (err.stack) console.error(err.stack);
    throw error;
  }
}
