/**
 * System Routes - Health check and routes listing
 *
 * AUTO-GENERATED by codegen (api_server_system_routes). Do not edit by hand.
 * Domains and routeExamples are derived from discovered api-server domains and
 * each domain's OpenAPI bundled spec.
 */

import type { FastifyInstance } from "fastify";
import {
  getCoreTableName,
  getBaseTableName,
  getAnalyticsTableName,
} from "@ledgerfit/adapters";
import { getRegisteredRoutes } from "./route-registry.js";

/**
 * Register system routes (health check, routes listing)
 */
export function registerSystemRoutes(fastify: FastifyInstance): void {
  // Health check (public - no auth required)
  fastify.get("/health", { config: { scope: "public" } }, async () => {
    try {
      const coreTable = getCoreTableName();
      const baseTable = getBaseTableName();
      const analyticsTable = getAnalyticsTableName();
      return {
        status: "ok",
        database: "dynamodb",
        tables: {
          core: coreTable,
          base: baseTable,
          analytics: analyticsTable,
        },
      };
    } catch (error: unknown) {
      const errorMessage =
        error instanceof Error ? error.message : String(error);
      fastify.log.warn({ error: errorMessage }, "Health check failed");
      return { status: "error", database: "disconnected", error: errorMessage };
    }
  });

  // Routes listing endpoint (public)
  fastify.get("/routes", { config: { scope: "public" } }, async () => {
    const domains = [
      "governance", "identity", "investigation", "ledgers", "models", "provenance", "training", "triggers"
    ];

    const routeExamples: Record<
      string,
      Array<{ method: string; path: string; description?: string }>
    > = {
      governance: [{ method: "GET", path: "/v1/threshold-policies" }, { method: "POST", path: "/v1/threshold-policies" }, { method: "GET", path: "/v1/threshold-policies/:policyId" }, { method: "POST", path: "/v1/threshold-policies/:policyId/approve" }, { method: "GET", path: "/v1/data-source-policies" }, { method: "POST", path: "/v1/data-source-policies" }, { method: "GET", path: "/v1/data-source-policies/:policyId" }],
      identity: [{ method: "GET", path: "/v0/tenants/me/api-keys" }, { method: "POST", path: "/v0/tenants/me/api-keys" }, { method: "GET", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "DELETE", path: "/v0/tenants/me/api-keys/:keyId" }, { method: "GET", path: "/v0/tenants/me/users" }, { method: "POST", path: "/v0/tenants/me/users" }, { method: "GET", path: "/v0/tenants/me/users/:userId" }, { method: "PATCH", path: "/v0/tenants/me/users/:userId" }, { method: "POST", path: "/v0/tenants/me/users/:userId/disable" }, { method: "POST", path: "/v0/tenants/me/users/:userId/enable" }, { method: "POST", path: "/v0/auth/login" }, { method: "GET", path: "/v0/auth/me" }, { method: "PATCH", path: "/v0/auth/me" }, { method: "POST", path: "/v0/auth/refresh" }, { method: "POST", path: "/v0/auth/logout" }],
      investigation: [{ method: "GET", path: "/v1/investigation/hits" }, { method: "GET", path: "/v1/investigation/reveals" }, { method: "POST", path: "/v1/investigation/reveals" }, { method: "GET", path: "/v1/investigation/reveals/:revealRequestId" }, { method: "POST", path: "/v1/investigation/reveals/:revealRequestId/decide" }, { method: "GET", path: "/v1/investigation/case-notes" }, { method: "POST", path: "/v1/investigation/case-notes" }],
      ledgers: [{ method: "GET", path: "/v1/ledgers" }, { method: "POST", path: "/v1/ledgers" }, { method: "GET", path: "/v1/ledgers/:ledgerId" }, { method: "GET", path: "/v1/ledgers/:ledgerId/members" }, { method: "POST", path: "/v1/ledgers/:ledgerId/members" }, { method: "GET", path: "/v1/ledgers/:ledgerId/events" }, { method: "POST", path: "/v1/ledgers/:ledgerId/events" }, { method: "POST", path: "/v1/members/:memberId/freeze" }, { method: "GET", path: "/v1/freeze-orders" }, { method: "POST", path: "/v1/freeze-orders/:freezeOrderId/acknowledge" }, { method: "POST", path: "/v1/freeze-orders/:freezeOrderId/release" }],
      models: [{ method: "GET", path: "/v1/model-artefacts" }, { method: "POST", path: "/v1/model-artefacts" }, { method: "GET", path: "/v1/model-artefacts/:artefactId" }, { method: "POST", path: "/v1/model-artefacts/:artefactId/promote" }, { method: "GET", path: "/v1/model-artefacts/:artefactId/rules" }],
      provenance: [{ method: "GET", path: "/v1/provenance" }, { method: "GET", path: "/v1/provenance/:recordId" }, { method: "POST", path: "/v1/provenance/export" }],
      training: [{ method: "GET", path: "/v1/training-jobs" }, { method: "POST", path: "/v1/training-jobs" }, { method: "GET", path: "/v1/training-jobs/:jobId" }, { method: "POST", path: "/v1/training-jobs/:jobId/cancel" }],
      triggers: [{ method: "GET", path: "/v1/smart-contract-triggers" }, { method: "POST", path: "/v1/smart-contract-triggers" }, { method: "GET", path: "/v1/smart-contract-triggers/:triggerId" }, { method: "PATCH", path: "/v1/smart-contract-triggers/:triggerId" }, { method: "POST", path: "/v1/smart-contract-triggers/:triggerId/fire" }],
    };

    return {
      baseUrl: "http://localhost:4000",
      routePattern: "/orgs/:orgId/{domain}/{resource}",
      authentication:
        "All routes (except /health and /routes) require JWT token in Authorization header",
      domains: domains.sort(),
      routeExamples,
      systemRoutes: [
        { method: "GET", path: "/health", description: "Health check endpoint" },
        { method: "GET", path: "/routes", description: "List available routes" },
      ],
      note: "Replace :orgId with actual organization ID. All domain routes require authentication.",
    };
  });

  // Full route list for API tester page (public)
  fastify.get("/routes/full", { config: { scope: "public" } }, async () => {
    const routes = getRegisteredRoutes();
    const byDomain: Record<
      string,
      Array<{ method: string; path: string }>
    > = {};
    const system: Array<{ method: string; path: string }> = [];
    for (const r of routes) {
      const m = r.path.match(/^\/orgs\/:orgId\/([^/]+)/);
      if (m) {
        const domain = m[1];
        if (!byDomain[domain]) byDomain[domain] = [];
        byDomain[domain].push(r);
      } else {
        system.push(r);
      }
    }
    return {
      baseUrl: "http://localhost:4000",
      total: routes.length,
      system,
      byDomain: Object.keys(byDomain)
        .sort()
        .reduce(
          (acc, k) => ({ ...acc, [k]: byDomain[k] }),
          {} as Record<string, Array<{ method: string; path: string }>>,
        ),
    };
  });
}
