/**
 * Repository interface for CaseNote
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  CaseNoteEntity
} from "../models/case-note.entity.js";
import type {
  ListCaseNotesParams,
  CaseNote
} from "../types/index.js";
/**
 * CaseNoteRepository Interface
 */
export interface CaseNoteRepository extends CreateReadRepository<CaseNoteEntity, CaseNote, string, ListCaseNotesParams> {

}
