/**
 * Handlers for Export
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProvenanceDomainModule } from "../dependencies/provenance-ddd.dependencies.js";
import type { ExportProvenanceAuditPackInput } from "@ledgerfit/services/provenance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/provenance/export
 * Operation: exportProvenanceAuditPack
 */
export async function exportProvenanceAuditPack(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: ProvenanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ExportProvenanceAuditPackInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.exports.list.execute(input);
  return reply.code(201).send(result);
}


