/**
 * Handlers for Provenance
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ProvenanceDomainModule } from "../dependencies/provenance-ddd.dependencies.js";
import type { GetProvenanceRecordInput, ListProvenanceRecordsInput } from "@ledgerfit/services/provenance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/provenance
 * Operation: listProvenanceRecords
 */
export async function listProvenanceRecords(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ProvenanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListProvenanceRecordsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.provenances.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for GET /v1/provenance/{recordId}
 * Operation: getProvenanceRecord
 */
export async function getProvenanceRecord(
  request: FastifyRequest<{ Params: { recordId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: ProvenanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetProvenanceRecordInput = {
    recordId: request.params.recordId,
  };
  const result = await deps.useCases.provenances.get.execute(input);
  return reply.code(200).send(result);
}


