/**
 * UpdateCancel DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { CancelTrainingJobParams } from "@ledgerfit/core/training";

export function createUpdateCancelRequest(overrides: Partial<CancelTrainingJobParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
