/**
 * DataSourcePolicy Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { DataSourcePolicyEntity } from "@ledgerfit/core/governance/models/index.js";
import { governanceSchemas } from "@ledgerfit/core/governance";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "gov";

export function createDataSourcePolicy(overrides: Partial<DataSourcePolicyEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    allowPublicChain: overrides.allowPublicChain ?? "False",
    allowSyntheticProduction: overrides.allowSyntheticProduction ?? "False",
    ledgerId: overrides.ledgerId ?? faker.string.uuid(),
    status: overrides.status ?? "active",
    ...overrides,
  };

  return governanceSchemas.DataSourcePolicy.parse(raw);
}

export function dataSourcePolicyBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createDataSourcePolicy(overrides));
}
