/**
 * CaseNote DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CaseNote DTOs
 *
 * DDD: Application DTOs for CaseNote use cases.
 */

import type { CreateCaseNoteRequestInput, ListCaseNotesParams } from "@ledgerfit/core/investigation/types";

export type ListCaseNotesInput = ListCaseNotesParams;

export type CreateCaseNoteInput = CreateCaseNoteRequestInput;

export type ListCaseNotesOutput = {};

export type CreateCaseNoteOutput = {};
