apis:
  identity:
    root: src/identity.yaml
  ledgers:
    root: src/ledgers.yaml
  training:
    root: src/training.yaml
  models:
    root: src/models.yaml
  triggers:
    root: src/triggers.yaml
  provenance:
    root: src/provenance.yaml
  investigation:
    root: src/investigation.yaml
  governance:
    root: src/governance.yaml

extends:
  - recommended

rules:
  no-unused-components: off
  operation-4xx-response: warn
  info-license: off
  info-license-url: off
  tag-description: off
  operation-operationId: error
  no-invalid-media-type-examples: off

theme:
  openapi:
    generateCodeSamples:
      languages: []
