/**
 * DataSourcePolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataSourcePolicy DTOs
 *
 * DDD: Application DTOs for DataSourcePolicy use cases.
 */

import type { CreateDataSourcePolicyRequestInput, GetDataSourcePolicyParams, ListDataSourcePoliciesParams } from "@ledgerfit/core/governance/types";

export type ListDataSourcePoliciesInput = ListDataSourcePoliciesParams;

export type CreateDataSourcePolicyInput = CreateDataSourcePolicyRequestInput;

export type GetDataSourcePolicyInput = GetDataSourcePolicyParams;

export type ListDataSourcePoliciesOutput = {};

export type CreateDataSourcePolicyOutput = {};

export type GetDataSourcePolicyOutput = {};
