/**
 * ThresholdPolicy DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ThresholdPolicy DTOs
 *
 * DDD: Application DTOs for ThresholdPolicy use cases.
 */

import type { CreateThresholdPolicyRequestInput, GetThresholdPolicyParams, ListThresholdPoliciesParams } from "@ledgerfit/core/governance/types";

export type ListThresholdPoliciesInput = ListThresholdPoliciesParams;

export type CreateThresholdPolicyInput = CreateThresholdPolicyRequestInput;

export type GetThresholdPolicyInput = GetThresholdPolicyParams;

export type ListThresholdPoliciesOutput = {};

export type CreateThresholdPolicyOutput = {};

export type GetThresholdPolicyOutput = {};
