/**
 * ExecuteListMaskedHits - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListMaskedHits Use Case
 *
 * DDD: Application use case for list Hit.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListMaskedHitsInput, ListMaskedHitsOutput } from "../dto/hit.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { HitRepository } from "../ports";

export class ExecuteListMaskedHits {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly hit: HitRepository
  ) {}

  async execute(input: ListMaskedHitsInput): Promise<ListMaskedHitsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.invId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.hit.listMaskedHits({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListMaskedHitsOutput;
  }
}
