/**
 * ExecuteCreateRevealRequest - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateRevealRequest Use Case
 *
 * DDD: Application use case for create Reveal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateRevealRequestInput, CreateRevealRequestOutput } from "../dto/reveal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { RevealRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateRevealRequest {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reveal: RevealRepository
  ) {}

  async execute(input: CreateRevealRequestInput): Promise<CreateRevealRequestOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.invId();

    // All field names extracted from OpenAPI spec: hitId, reason
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.reason) {
      throw new ValidationError("reason is required");
    }
    if (!input.hitId) {
      throw new ValidationError("hitId is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (investigation domain)
    const entityId = this.idGenerator.invId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.reveal.createRevealRequest({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateRevealRequestOutput;
  }
}
