/**
 * ExecuteListRevealRequests - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListRevealRequests Use Case
 *
 * DDD: Application use case for list Reveal.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListRevealRequestsInput, ListRevealRequestsOutput } from "../dto/reveal.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { RevealRepository } from "../ports";

export class ExecuteListRevealRequests {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly reveal: RevealRepository
  ) {}

  async execute(input: ListRevealRequestsInput): Promise<ListRevealRequestsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.invId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.reveal.listRevealRequests({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListRevealRequestsOutput;
  }
}
