/**
 * Event DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Event DTOs
 *
 * DDD: Application DTOs for Event use cases.
 */

import type { AnchorPrescriptionEventParams, AnchorPrescriptionEventRequestInput, ListPrescriptionEventRefsParams } from "@ledgerfit/core/ledgers/types";

export type ListPrescriptionEventRefsInput = ListPrescriptionEventRefsParams;

export type AnchorPrescriptionEventInput = AnchorPrescriptionEventParams & AnchorPrescriptionEventRequestInput;

export type ListPrescriptionEventRefsOutput = {};

export type AnchorPrescriptionEventOutput = {};
