/**
 * Ledger DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Ledger DTOs
 *
 * DDD: Application DTOs for Ledger use cases.
 */

import type { GetLedgerParams, ListLedgersParams, RegisterLedgerRequestInput } from "@ledgerfit/core/ledgers/types";

export type ListLedgersInput = ListLedgersParams;

export type RegisterLedgerInput = RegisterLedgerRequestInput;

export type GetLedgerInput = GetLedgerParams;

export type ListLedgersOutput = {};

export type RegisterLedgerOutput = {};

export type GetLedgerOutput = {};
