/**
 * Member DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Member DTOs
 *
 * DDD: Application DTOs for Member use cases.
 */

import type { AddPharmacyMemberParams, AddPharmacyMemberRequestInput, ListPharmacyMembersParams } from "@ledgerfit/core/ledgers/types";

export type ListPharmacyMembersInput = ListPharmacyMembersParams;

export type AddPharmacyMemberInput = AddPharmacyMemberParams & AddPharmacyMemberRequestInput;

export type ListPharmacyMembersOutput = {};

export type AddPharmacyMemberOutput = {};
