/**
 * Release DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Release DTOs
 *
 * DDD: Application DTOs for Release use cases.
 */

import type { ReleaseFreezeOrderParams } from "@ledgerfit/core/ledgers/types";

export type ReleaseFreezeOrderInput = ReleaseFreezeOrderParams;

export type ReleaseFreezeOrderOutput = {};
