/**
 * Governance DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Governance Domain Module - Composition root
 *
 * DDD: Composition root for governance domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  ApproveRepositoryAdapter,
  DataSourcePolicyRepositoryAdapter,
  ThresholdPolicyRepositoryAdapter,
} from "@ledgerfit/adapters/governance";
import { getIdGeneratorService } from "@ledgerfit/adapters";
import type { AdapterDynamoDBClient } from "@ledgerfit/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteApproveThresholdPolicy,
  ExecuteCreateDataSourcePolicy,
  ExecuteCreateThresholdPolicy,
  ExecuteGetDataSourcePolicy,
  ExecuteGetThresholdPolicy,
  ExecuteListDataSourcePolicies,
  ExecuteListThresholdPolicies,
} from "@ledgerfit/services/governance/usecases";
// Ports (interfaces)
import type {
  ApproveRepository,
  DataSourcePolicyRepository,
  ThresholdPolicyRepository,
} from "@ledgerfit/services/governance/ports";

export interface GovernanceDomainModule {
  repos: {
    approves: ApproveRepository;
    dataSourcePolicies: DataSourcePolicyRepository;
    thresholdPolicies: ThresholdPolicyRepository;
  };
  useCases: {
    approves: {
      create: ExecuteApproveThresholdPolicy;
    };
    dataSourcePolicies: {
      create: ExecuteCreateDataSourcePolicy;
      get: ExecuteGetDataSourcePolicy;
      list: ExecuteListDataSourcePolicies;
    };
    thresholdPolicies: {
      create: ExecuteCreateThresholdPolicy;
      get: ExecuteGetThresholdPolicy;
      list: ExecuteListThresholdPolicies;
    };
  };
}

export function buildGovernanceDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): GovernanceDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      approves?: ApproveRepository;
      dataSourcePolicies?: DataSourcePolicyRepository;
      thresholdPolicies?: ThresholdPolicyRepository;
    } = {};

    obj.approves = new ApproveRepositoryAdapter(dynamoClient);
    obj.dataSourcePolicies = new DataSourcePolicyRepositoryAdapter(dynamoClient);
    obj.thresholdPolicies = new ThresholdPolicyRepositoryAdapter(dynamoClient);
    return {
      approves: obj.approves!,
      dataSourcePolicies: obj.dataSourcePolicies!,
      thresholdPolicies: obj.thresholdPolicies!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    approves: {
      create: new ExecuteApproveThresholdPolicy(executionContext, idGenerator, repos.approves),
    },
    dataSourcePolicies: {
      create: new ExecuteCreateDataSourcePolicy(executionContext, idGenerator, repos.dataSourcePolicies),
      get: new ExecuteGetDataSourcePolicy(executionContext, idGenerator, repos.dataSourcePolicies),
      list: new ExecuteListDataSourcePolicies(executionContext, idGenerator, repos.dataSourcePolicies),
    },
    thresholdPolicies: {
      create: new ExecuteCreateThresholdPolicy(executionContext, idGenerator, repos.thresholdPolicies),
      get: new ExecuteGetThresholdPolicy(executionContext, idGenerator, repos.thresholdPolicies),
      list: new ExecuteListThresholdPolicies(executionContext, idGenerator, repos.thresholdPolicies),
    },
  };
  return { repos, useCases: useCases as GovernanceDomainModule["useCases"] };
}
