/**
 * Main Core Package Index
 *
 * Generated by Main Index Builder Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * @ledgerfit/core - Main Barrel Export
 *
 * Central export point for all core business logic, entities, repositories, and types
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended for new code)
 *   import { activity, ai } from "@ledgerfit/core";
 *   const { repositories, types } = activity;
 *
 *   // Direct domain imports (via package.json exports)
 *   import { ActivityRepository } from "@ledgerfit/core/activity/repositories/index.js";
 *   import { ActivityEntity } from "@ledgerfit/core/activity/models/index.js";
 *   import { ActivitySchemas } from "@ledgerfit/core/activity/schemas/index.js";
 *
 *   // Flat schema imports
 *   import { ActivitySchemas, AiSchemas } from "@ledgerfit/core";
 */

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate shared type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types (AccountId, OrgId, PageInfo, components, operations)
// NOTE: _shared is NOT a domain and is exported separately

import * as __shared from "./_shared/index.js";
import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _investigation from "./investigation/index.js";
import * as _ledgers from "./ledgers/index.js";
import * as _models from "./models/index.js";
import * as _provenance from "./provenance/index.js";
import * as _training from "./training/index.js";
import * as _triggers from "./triggers/index.js";

// Export as namespaces
export const _shared = __shared;
export const governance = _governance;
export const identity = _identity;
export const investigation = _investigation;
export const ledgers = _ledgers;
export const models = _models;
export const provenance = _provenance;
export const training = _training;
export const triggers = _triggers;

// ============================================================================
// FLAT EXPORTS (for direct imports)
// ============================================================================
// Export schemas from each domain for convenience
// NOTE: Types, repositories, models, and value-objects are available via:
//   - Namespace exports: import { activity } from "@ledgerfit/core"; activity.types.*
//   - Direct exports: import * from "@ledgerfit/core/activity/types/index.js"
//   - Direct exports: import * from "@ledgerfit/core/activity/repositories/index.js"
//   - Direct exports: import * from "@ledgerfit/core/activity/models/index.js"
//   - Direct exports: import * from "@ledgerfit/core/activity/value-objects/index.js"

// Shared utilities and helpers
// These exports are required by platform/api-server and platform/services
export {
  DOMAIN_PREFIX_MAP,
  isValidDomainId,
  extractDomainFromId,
} from "./_shared/index.js";
export type { DomainCode, DomainPrefix } from "./_shared/index.js";

// Governance Service
export { schemas as GovernanceSchemas } from "./governance/schemas/governance.schemas.js";

// Identity Service
export { schemas as IdentitySchemas } from "./identity/schemas/identity.schemas.js";

// Investigation Service
export { schemas as InvestigationSchemas } from "./investigation/schemas/investigation.schemas.js";

// Ledgers Service
export { schemas as LedgersSchemas } from "./ledgers/schemas/ledgers.schemas.js";

// Models Service
export { schemas as ModelsSchemas } from "./models/schemas/models.schemas.js";

// Provenance Service
export { schemas as ProvenanceSchemas } from "./provenance/schemas/provenance.schemas.js";

// Training Service
export { schemas as TrainingSchemas } from "./training/schemas/training.schemas.js";

// Triggers Service
export { schemas as TriggersSchemas } from "./triggers/schemas/triggers.schemas.js";

