/**
 * DataSourcePolicyRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataSourcePolicyRepository Port
 *
 * DDD: Application port for datasourcepolicyrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateDataSourcePolicyInput, CreateDataSourcePolicyOutput, GetDataSourcePolicyInput, GetDataSourcePolicyOutput, ListDataSourcePoliciesInput, ListDataSourcePoliciesOutput } from "../dto/data-source-policy.dto";
export interface DataSourcePolicyRepository {
  listDataSourcePolicies(input: ListDataSourcePoliciesInput): Promise<ListDataSourcePoliciesOutput>;
  createDataSourcePolicy(input: CreateDataSourcePolicyInput): Promise<CreateDataSourcePolicyOutput>;
  getDataSourcePolicy(input: GetDataSourcePolicyInput): Promise<GetDataSourcePolicyOutput>;
}

export type { CreateDataSourcePolicyInput, CreateDataSourcePolicyOutput, GetDataSourcePolicyInput, GetDataSourcePolicyOutput, ListDataSourcePoliciesInput, ListDataSourcePoliciesOutput } from "../dto/data-source-policy.dto";
