/**
 * ExecuteApproveThresholdPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteApproveThresholdPolicy Use Case
 *
 * DDD: Application use case for create Approve.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ApproveThresholdPolicyInput, ApproveThresholdPolicyOutput } from "../dto/approve.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { ApproveRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteApproveThresholdPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly approve: ApproveRepository
  ) {}

  async execute(input: ApproveThresholdPolicyInput): Promise<ApproveThresholdPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: approverNote
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.approverNote) {
      throw new ValidationError("approverNote is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (governance domain)
    const entityId = this.idGenerator.govId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.approve.approveThresholdPolicy({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as ApproveThresholdPolicyOutput;
  }
}
