/**
 * ExecuteListDataSourcePolicies - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListDataSourcePolicies Use Case
 *
 * DDD: Application use case for list DataSourcePolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListDataSourcePoliciesInput, ListDataSourcePoliciesOutput } from "../dto/data-source-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { DataSourcePolicyRepository } from "../ports";

export class ExecuteListDataSourcePolicies {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly dataSourcePolicy: DataSourcePolicyRepository
  ) {}

  async execute(input: ListDataSourcePoliciesInput): Promise<ListDataSourcePoliciesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.dataSourcePolicy.listDataSourcePolicies({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListDataSourcePoliciesOutput;
  }
}
