/**
 * ExecuteGetThresholdPolicy - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetThresholdPolicy Use Case
 *
 * DDD: Application use case for get ThresholdPolicy.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetThresholdPolicyInput, GetThresholdPolicyOutput } from "../dto/threshold-policy.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { ThresholdPolicyRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetThresholdPolicy {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly thresholdPolicy: ThresholdPolicyRepository
  ) {}

  async execute(input: GetThresholdPolicyInput): Promise<GetThresholdPolicyOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.govId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).policyId) {
      throw new ValidationError("policyId is required");
    }
    const policyId = (input as any).policyId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.thresholdPolicy.getThresholdPolicy({ policyId: policyId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${policyId}`);
    }

    return entity as GetThresholdPolicyOutput;
  }
}
