/**
 * DynamoDB repository adapters barrel export
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./model-artefact-repository.ddb.js";
export * from "./promote-repository.ddb.js";
export * from "./rule-repository.ddb.js";
export * from "./model-artefact-repository.adapter.js";
export * from "./promote-repository.adapter.js";
export * from "./rule-repository.adapter.js";
