/**
 * ModelArtefactRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ModelArtefactRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ModelArtefactRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ModelArtefactRepository,
} from "@ledgerfit/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ModelArtefactRepositoryDdb } from "./model-artefact-repository.ddb.js";

/**
 * ModelArtefactRepositoryAdapter
 *
 * Implements ModelArtefactRepository port for infrastructure layer.
 */
export class ModelArtefactRepositoryAdapter implements ModelArtefactRepository {
  private readonly ddb: ModelArtefactRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ModelArtefactRepositoryDdb(this.dynamoClient);
  }

  async listModelArtefacts(input: Parameters<ModelArtefactRepository['listModelArtefacts']>[0]): Promise<Awaited<ReturnType<ModelArtefactRepository['listModelArtefacts']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listModelArtefacts(input);
  }

  async registerModelArtefact(input: Parameters<ModelArtefactRepository['registerModelArtefact']>[0]): Promise<Awaited<ReturnType<ModelArtefactRepository['registerModelArtefact']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.registerModelArtefact(input);
  }

  async getModelArtefact(input: Parameters<ModelArtefactRepository['getModelArtefact']>[0]): Promise<Awaited<ReturnType<ModelArtefactRepository['getModelArtefact']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getModelArtefact(input);
  }
}
