/**
 * RuleRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RuleRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RuleRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RuleRepository,
} from "@ledgerfit/services/models";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RuleRepositoryDdb } from "./rule-repository.ddb.js";

/**
 * RuleRepositoryAdapter
 *
 * Implements RuleRepository port for infrastructure layer.
 */
export class RuleRepositoryAdapter implements RuleRepository {
  private readonly ddb: RuleRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RuleRepositoryDdb(this.dynamoClient);
  }

  async listAssociationRules(input: Parameters<RuleRepository['listAssociationRules']>[0]): Promise<Awaited<ReturnType<RuleRepository['listAssociationRules']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listAssociationRules(input);
  }
}
