/**
 * CaseNoteRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CaseNoteRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements CaseNoteRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  CaseNoteRepository,
} from "@ledgerfit/services/investigation";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { CaseNoteRepositoryDdb } from "./case-note-repository.ddb.js";

/**
 * CaseNoteRepositoryAdapter
 *
 * Implements CaseNoteRepository port for infrastructure layer.
 */
export class CaseNoteRepositoryAdapter implements CaseNoteRepository {
  private readonly ddb: CaseNoteRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new CaseNoteRepositoryDdb(this.dynamoClient);
  }

  async listCaseNotes(input: Parameters<CaseNoteRepository['listCaseNotes']>[0]): Promise<Awaited<ReturnType<CaseNoteRepository['listCaseNotes']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listCaseNotes(input);
  }

  async createCaseNote(input: Parameters<CaseNoteRepository['createCaseNote']>[0]): Promise<Awaited<ReturnType<CaseNoteRepository['createCaseNote']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createCaseNote(input);
  }
}
