/**
 * HitRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HitRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements HitRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  HitRepository,
} from "@ledgerfit/services/investigation";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { HitRepositoryDdb } from "./hit-repository.ddb.js";

/**
 * HitRepositoryAdapter
 *
 * Implements HitRepository port for infrastructure layer.
 */
export class HitRepositoryAdapter implements HitRepository {
  private readonly ddb: HitRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new HitRepositoryDdb(this.dynamoClient);
  }

  async listMaskedHits(input: Parameters<HitRepository['listMaskedHits']>[0]): Promise<Awaited<ReturnType<HitRepository['listMaskedHits']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listMaskedHits(input);
  }
}
