/**
 * RevealRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RevealRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements RevealRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  RevealRepository,
} from "@ledgerfit/services/investigation";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { RevealRepositoryDdb } from "./reveal-repository.ddb.js";

/**
 * RevealRepositoryAdapter
 *
 * Implements RevealRepository port for infrastructure layer.
 */
export class RevealRepositoryAdapter implements RevealRepository {
  private readonly ddb: RevealRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new RevealRepositoryDdb(this.dynamoClient);
  }

  async listRevealRequests(input: Parameters<RevealRepository['listRevealRequests']>[0]): Promise<Awaited<ReturnType<RevealRepository['listRevealRequests']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listRevealRequests(input);
  }

  async createRevealRequest(input: Parameters<RevealRepository['createRevealRequest']>[0]): Promise<Awaited<ReturnType<RevealRepository['createRevealRequest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createRevealRequest(input);
  }

  async getRevealRequest(input: Parameters<RevealRepository['getRevealRequest']>[0]): Promise<Awaited<ReturnType<RevealRepository['getRevealRequest']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getRevealRequest(input);
  }
}
