/**
 * GetReveal DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { GetRevealRequestParams } from "@ledgerfit/core/investigation";

export function createGetRevealRequest(overrides: Partial<GetRevealRequestParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
