/**
 * ModelArtefact Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { ModelArtefactEntity } from "@ledgerfit/core/models/models/index.js";
import { modelsSchemas } from "@ledgerfit/core/models";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "mdl";

export function createModelArtefact(overrides: Partial<ModelArtefactEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    algorithm: overrides.algorithm ?? faker.lorem.word(),
    contentDigest: overrides.contentDigest ?? faker.lorem.word(),
    dataLabel: overrides.dataLabel ?? "synthetic",
    jobId: overrides.jobId ?? faker.string.uuid(),
    ledgerId: overrides.ledgerId ?? faker.string.uuid(),
    promotionState: overrides.promotionState ?? "experimental",
    ...overrides,
  };

  return modelsSchemas.ModelArtefact.parse(raw);
}

export function modelArtefactBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createModelArtefact(overrides));
}
