/**
 * SmartContractTrigger Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { SmartContractTriggerEntity } from "@ledgerfit/core/triggers/models/index.js";
import { triggersSchemas } from "@ledgerfit/core/triggers";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "trg";

export function createSmartContractTrigger(overrides: Partial<SmartContractTriggerEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    condition: overrides.condition ?? "newBlocksThreshold",
    enabled: overrides.enabled ?? faker.datatype.boolean(),
    ledgerId: overrides.ledgerId ?? faker.string.uuid(),
    lifecycleStep: overrides.lifecycleStep ?? "modelInitialization",
    name: overrides.name ?? faker.person.fullName(),
    ...overrides,
  };

  return triggersSchemas.SmartContractTrigger.parse(raw);
}

export function smartContractTriggerBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createSmartContractTrigger(overrides));
}
