/**
 * ExecuteListAssociationRules - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListAssociationRules Use Case
 *
 * DDD: Application use case for list Rule.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListAssociationRulesInput, ListAssociationRulesOutput } from "../dto/rule.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { RuleRepository } from "../ports";

export class ExecuteListAssociationRules {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly rule: RuleRepository
  ) {}

  async execute(input: ListAssociationRulesInput): Promise<ListAssociationRulesOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mdlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.rule.listAssociationRules({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListAssociationRulesOutput;
  }
}
