/**
 * ExecuteListModelArtefacts - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListModelArtefacts Use Case
 *
 * DDD: Application use case for list ModelArtefact.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListModelArtefactsInput, ListModelArtefactsOutput } from "../dto/model-artefact.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { ModelArtefactRepository } from "../ports";

export class ExecuteListModelArtefacts {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly modelArtefact: ModelArtefactRepository
  ) {}

  async execute(input: ListModelArtefactsInput): Promise<ListModelArtefactsOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mdlId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.modelArtefact.listModelArtefacts({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListModelArtefactsOutput;
  }
}
