/**
 * ExecuteGetModelArtefact - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteGetModelArtefact Use Case
 *
 * DDD: Application use case for get ModelArtefact.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { GetModelArtefactInput, GetModelArtefactOutput } from "../dto/model-artefact.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { ModelArtefactRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteGetModelArtefact {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly modelArtefact: ModelArtefactRepository
  ) {}

  async execute(input: GetModelArtefactInput): Promise<GetModelArtefactOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.mdlId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).artefactId) {
      throw new ValidationError("artefactId is required");
    }
    const artefactId = (input as any).artefactId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.modelArtefact.getModelArtefact({ artefactId: artefactId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${artefactId}`);
    }

    return entity as GetModelArtefactOutput;
  }
}
