/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Investigation Domain Use Cases
 * 
 * List of all use case names for the investigation domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const INVESTIGATION_USE_CASES = [
  "executeCreateCaseNote",
  "executeCreateRevealRequest",
  "executeDecideRevealRequest",
  "executeGetRevealRequest",
  "executeListCaseNotes",
  "executeListMaskedHits",
  "executeListRevealRequests"
] as const;
