/**
 * CreateFire DTO Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import type { FireSmartContractTriggerParams } from "@ledgerfit/core/triggers";

export function createCreateFireRequest(overrides: Partial<FireSmartContractTriggerParams> = {}) {
  const raw = {
    ...overrides,
  };

  return raw;
}
