/**
 * ProvenanceRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ProvenanceRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ProvenanceRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ProvenanceRepository,
} from "@ledgerfit/services/provenance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ProvenanceRepositoryDdb } from "./provenance-repository.ddb.js";

/**
 * ProvenanceRepositoryAdapter
 *
 * Implements ProvenanceRepository port for infrastructure layer.
 */
export class ProvenanceRepositoryAdapter implements ProvenanceRepository {
  private readonly ddb: ProvenanceRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ProvenanceRepositoryDdb(this.dynamoClient);
  }

  async listProvenanceRecords(input: Parameters<ProvenanceRepository['listProvenanceRecords']>[0]): Promise<Awaited<ReturnType<ProvenanceRepository['listProvenanceRecords']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listProvenanceRecords(input);
  }

  async getProvenanceRecord(input: Parameters<ProvenanceRepository['getProvenanceRecord']>[0]): Promise<Awaited<ReturnType<ProvenanceRepository['getProvenanceRecord']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getProvenanceRecord(input);
  }
}
