/**
 * Routes for Ledger
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { getLedger, listLedgers, registerLedger } from "../handlers/ledger.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function ledgerRoutes(fastify: FastifyInstance) {
  // GET /v1/ledgers (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/ledgers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLedgersDependenciesForRequest();
        await listLedgers(request, reply, deps);
      });
    }
  );


  // POST /v1/ledgers (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/ledgers",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLedgersDependenciesForRequest();
        await registerLedger(request, reply, deps);
      });
    }
  );


  // GET /v1/ledgers/{ledgerId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/ledgers/:ledgerId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { ledgerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLedgersDependenciesForRequest();
        await getLedger(request, reply, deps);
      });
    }
  );


}
