/**
 * Routes for Member
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { addPharmacyMember, listPharmacyMembers } from "../handlers/member.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function memberRoutes(fastify: FastifyInstance) {
  // POST /v1/ledgers/{ledgerId}/members (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/ledgers/:ledgerId/members",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { ledgerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLedgersDependenciesForRequest();
        await addPharmacyMember(request, reply, deps);
      });
    }
  );


  // GET /v1/ledgers/{ledgerId}/members (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/ledgers/:ledgerId/members",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { ledgerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getLedgersDependenciesForRequest();
        await listPharmacyMembers(request, reply, deps);
      });
    }
  );


}
