/**
 * Handlers for Fire
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TriggersDomainModule } from "../dependencies/triggers-ddd.dependencies.js";
import type { FireSmartContractTriggerInput } from "@ledgerfit/services/triggers";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/smart-contract-triggers/{triggerId}/fire
 * Operation: fireSmartContractTrigger
 */
export async function fireSmartContractTrigger(
  request: FastifyRequest<{ Params: { triggerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TriggersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: FireSmartContractTriggerInput = {
    triggerId: request.params.triggerId,
  };
  const result = await deps.useCases.fires.get.execute(input);
  return reply.code(200).send(result);
}


