/**
 * Handlers for SmartContractTrigger
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { TriggersDomainModule } from "../dependencies/triggers-ddd.dependencies.js";
import type { CreateSmartContractTriggerInput, GetSmartContractTriggerInput, ListSmartContractTriggersInput, UpdateSmartContractTriggerInput } from "@ledgerfit/services/triggers";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/smart-contract-triggers
 * Operation: listSmartContractTriggers
 */
export async function listSmartContractTriggers(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: TriggersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListSmartContractTriggersInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.smartContractTriggers.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/smart-contract-triggers
 * Operation: createSmartContractTrigger
 */
export async function createSmartContractTrigger(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: TriggersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateSmartContractTriggerInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.smartContractTriggers.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/smart-contract-triggers/{triggerId}
 * Operation: getSmartContractTrigger
 */
export async function getSmartContractTrigger(
  request: FastifyRequest<{ Params: { triggerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TriggersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetSmartContractTriggerInput = {
    triggerId: request.params.triggerId,
  };
  const result = await deps.useCases.smartContractTriggers.get.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for PATCH /v1/smart-contract-triggers/{triggerId}
 * Operation: updateSmartContractTrigger
 */
export async function updateSmartContractTrigger(
  request: FastifyRequest<{ Params: { triggerId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: TriggersDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: UpdateSmartContractTriggerInput = {
    triggerId: request.params.triggerId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.smartContractTriggers.update.execute(input);
  return reply.code(200).send(result);
}


