/**
 * Fire DTOs - Application DTOs
 *
 * Generated by DTO Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Fire DTOs
 *
 * DDD: Application DTOs for Fire use cases.
 */

import type { FireSmartContractTriggerParams } from "@ledgerfit/core/triggers/types";

export type FireSmartContractTriggerInput = FireSmartContractTriggerParams;

export type FireSmartContractTriggerOutput = {};
