/**
 * Domains Barrel Export
 *
 * AUTO-GENERATED by codegen (api_server_domain_routes). Do not edit by hand.
 * Centralized exports for all domain dependency builders and types.
 */

// Export all domain dependency builders
export { buildGovernanceDomainModule } from "./governance/dependencies/governance-ddd.dependencies.js";
export { buildIdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export { buildInvestigationDomainModule } from "./investigation/dependencies/investigation-ddd.dependencies.js";
export { buildLedgersDomainModule } from "./ledgers/dependencies/ledgers-ddd.dependencies.js";
export { buildModelsDomainModule } from "./models/dependencies/models-ddd.dependencies.js";
export { buildProvenanceDomainModule } from "./provenance/dependencies/provenance-ddd.dependencies.js";
export { buildTrainingDomainModule } from "./training/dependencies/training-ddd.dependencies.js";
export { buildTriggersDomainModule } from "./triggers/dependencies/triggers-ddd.dependencies.js";

// Export all domain dependency types
export type { GovernanceDomainModule } from "./governance/dependencies/governance-ddd.dependencies.js";
export type { IdentityDomainModule } from "./identity/dependencies/identity-ddd.dependencies.js";
export type { InvestigationDomainModule } from "./investigation/dependencies/investigation-ddd.dependencies.js";
export type { LedgersDomainModule } from "./ledgers/dependencies/ledgers-ddd.dependencies.js";
export type { ModelsDomainModule } from "./models/dependencies/models-ddd.dependencies.js";
export type { ProvenanceDomainModule } from "./provenance/dependencies/provenance-ddd.dependencies.js";
export type { TrainingDomainModule } from "./training/dependencies/training-ddd.dependencies.js";
export type { TriggersDomainModule } from "./triggers/dependencies/triggers-ddd.dependencies.js";
