/**
 * Repository interface for SmartContractTrigger
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  CreateUpdateReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  SmartContractTriggerEntity
} from "../models/smart-contract-trigger.entity.js";
import type {
  ListSmartContractTriggersParams,
  SmartContractTrigger,
  UpdateSmartContractTriggerRequestInput
} from "../types/index.js";
/**
 * SmartContractTriggerRepository Interface
 */
export interface SmartContractTriggerRepository extends CreateUpdateReadRepository<SmartContractTriggerEntity, SmartContractTrigger, UpdateSmartContractTriggerRequestInput, string, ListSmartContractTriggersParams> {

}
