/**
 * CaseNote Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { CaseNoteEntity } from "@ledgerfit/core/investigation/models/index.js";
import { investigationSchemas } from "@ledgerfit/core/investigation";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "inv";

export function createCaseNote(overrides: Partial<CaseNoteEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    authorId: overrides.authorId ?? faker.string.uuid(),
    body: overrides.body ?? faker.lorem.paragraph(),
    hitId: overrides.hitId ?? faker.string.uuid(),
    ...overrides,
  };

  return investigationSchemas.CaseNote.parse(raw);
}

export function caseNoteBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createCaseNote(overrides));
}
