/**
 * SmartContractTriggerRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * SmartContractTriggerRepository Port
 *
 * DDD: Application port for smartcontracttriggerrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateSmartContractTriggerInput, CreateSmartContractTriggerOutput, GetSmartContractTriggerInput, GetSmartContractTriggerOutput, ListSmartContractTriggersInput, ListSmartContractTriggersOutput, UpdateSmartContractTriggerInput, UpdateSmartContractTriggerOutput } from "../dto/smart-contract-trigger.dto";
export interface SmartContractTriggerRepository {
  listSmartContractTriggers(input: ListSmartContractTriggersInput): Promise<ListSmartContractTriggersOutput>;
  createSmartContractTrigger(input: CreateSmartContractTriggerInput): Promise<CreateSmartContractTriggerOutput>;
  getSmartContractTrigger(input: GetSmartContractTriggerInput): Promise<GetSmartContractTriggerOutput>;
  updateSmartContractTrigger(input: UpdateSmartContractTriggerInput): Promise<UpdateSmartContractTriggerOutput>;
}

export type { CreateSmartContractTriggerInput, CreateSmartContractTriggerOutput, GetSmartContractTriggerInput, GetSmartContractTriggerOutput, ListSmartContractTriggersInput, ListSmartContractTriggersOutput, UpdateSmartContractTriggerInput, UpdateSmartContractTriggerOutput } from "../dto/smart-contract-trigger.dto";
