/**
 * RuleRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * RuleRepository Port
 *
 * DDD: Application port for rulerepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListAssociationRulesInput, ListAssociationRulesOutput } from "../dto/rule.dto";
export interface RuleRepository {
  listAssociationRules(input: ListAssociationRulesInput): Promise<ListAssociationRulesOutput>;
}

export type { ListAssociationRulesInput, ListAssociationRulesOutput } from "../dto/rule.dto";
