/**
 * CreateSmartContractTrigger handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { createSmartContractTrigger } from "@ledgerfit/api-server/domains/triggers/handlers";
import type { TriggersDDDDependencies } from "@ledgerfit/api-server/domains/triggers";
import { createSmartContractTrigger as createSmartContractTriggerEntity } from "@ledgerfit/factories/triggers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { TRIGGERS_USE_CASES } from "../__factories__/use-cases.js";

describe("CreateSmartContractTrigger", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TriggersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TriggersDDDDependencies>(
      TRIGGERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = {} as any;
    const entity = createSmartContractTriggerEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeCreateSmartContractTrigger, "execute").mockResolvedValue(useCaseResult);

    await createSmartContractTrigger(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeCreateSmartContractTrigger.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(201);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
