/**
 * GetSmartContractTrigger handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getSmartContractTrigger } from "@ledgerfit/api-server/domains/triggers/handlers";
import type { TriggersDDDDependencies } from "@ledgerfit/api-server/domains/triggers";
import { createSmartContractTrigger as createSmartContractTriggerEntity } from "@ledgerfit/factories/triggers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { TRIGGERS_USE_CASES } from "../__factories__/use-cases.js";

describe("GetSmartContractTrigger", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TriggersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TriggersDDDDependencies>(
      TRIGGERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createSmartContractTriggerEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetSmartContractTrigger, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { triggerId: entity.id };

    await getSmartContractTrigger(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetSmartContractTrigger.execute).toHaveBeenCalledWith(expect.objectContaining({ triggerId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { triggerId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetSmartContractTrigger, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getSmartContractTrigger(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
