/**
 * Handler tests barrel export
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./create-smart-contract-trigger.handler.test.js";
export * from "./get-smart-contract-trigger.handler.test.js";
export * from "./list-smart-contract-triggers.handler.test.js";
export * from "./update-smart-contract-trigger.handler.test.js";
