/**
 * ListSmartContractTriggers handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listSmartContractTriggers } from "@ledgerfit/api-server/domains/triggers/handlers";
import type { TriggersDDDDependencies } from "@ledgerfit/api-server/domains/triggers";
import { createSmartContractTrigger as createSmartContractTriggerEntity } from "@ledgerfit/factories/triggers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { TRIGGERS_USE_CASES } from "../__factories__/use-cases.js";

describe("ListSmartContractTriggers", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TriggersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TriggersDDDDependencies>(
      TRIGGERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createSmartContractTriggerEntity({ orgId }),
      createSmartContractTriggerEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListSmartContractTriggers, "execute").mockResolvedValue(useCaseResult);

    await listSmartContractTriggers(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListSmartContractTriggers.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
