/**
 * CaseNoteRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * CaseNoteRepository Port
 *
 * DDD: Application port for casenoterepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { CreateCaseNoteInput, CreateCaseNoteOutput, ListCaseNotesInput, ListCaseNotesOutput } from "../dto/case-note.dto";
export interface CaseNoteRepository {
  listCaseNotes(input: ListCaseNotesInput): Promise<ListCaseNotesOutput>;
  createCaseNote(input: CreateCaseNoteInput): Promise<CreateCaseNoteOutput>;
}

export type { CreateCaseNoteInput, CreateCaseNoteOutput, ListCaseNotesInput, ListCaseNotesOutput } from "../dto/case-note.dto";
