/**
 * HitRepository Port - Application port interface
 *
 * Generated by Port Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * HitRepository Port
 *
 * DDD: Application port for hitrepository operations.
 * This is an application-level abstraction, not a domain concept.
 * Implementations live in adapters layer.
 */

import type { ListMaskedHitsInput, ListMaskedHitsOutput } from "../dto/hit.dto";
export interface HitRepository {
  listMaskedHits(input: ListMaskedHitsInput): Promise<ListMaskedHitsOutput>;
}

export type { ListMaskedHitsInput, ListMaskedHitsOutput } from "../dto/hit.dto";
