/**
 * Main Services Package Index
 *
 * Generated by Services Main Index Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: identity
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Services Package - Main Barrel Export
 *
 * Central export point for all application services (use cases, ports, DTOs, policies, errors)
 * Organized by domain for easy importing
 *
 * Usage:
 *   // Namespace imports (recommended)
 *   import { activity, ai, conversation } from "@ledgerfit/services";
 *   const { usecases, dto, ports } = activity;
 *
 *   // Direct imports from domain
 *   import { ExecuteCreateEventUseCase } from "@ledgerfit/services/activity";
 *   
 *   // Shared services
 *   import { executionContextService } from "@ledgerfit/services";
 */

// ============================================================================
// SHARED SERVICES EXPORTS
// ============================================================================
export { executionContextService } from "./_shared/index.js";

// ============================================================================
// DOMAIN EXPORTS (using namespace to avoid duplicate type conflicts)
// ============================================================================
// Export domains as namespaces to prevent TS2308 errors from duplicate exports
// of shared types across domains

import * as _governance from "./governance/index.js";
import * as _identity from "./identity/index.js";
import * as _investigation from "./investigation/index.js";
import * as _ledgers from "./ledgers/index.js";
import * as _models from "./models/index.js";
import * as _provenance from "./provenance/index.js";
import * as _training from "./training/index.js";
import * as _triggers from "./triggers/index.js";

// Export as namespaces
export const governance = _governance;
export const identity = _identity;
export const investigation = _investigation;
export const ledgers = _ledgers;
export const models = _models;
export const provenance = _provenance;
export const training = _training;
export const triggers = _triggers;
