/**
 * Repository interface for FreezeOrder
 *
 * Generated by Repository Generator v1.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type {
  ReadRepository,
} from "../../_shared/repositories/_base-repository.js";

import type {
  FreezeOrderEntity
} from "../models/freeze-order.entity.js";
import type {
  ListFreezeOrdersParams
} from "../types/index.js";
/**
 * FreezeOrderRepository Interface
 */
export interface FreezeOrderRepository extends ReadRepository<FreezeOrderEntity, string, ListFreezeOrdersParams> {

}
