/**
 * FireSmartContractTrigger handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { fireSmartContractTrigger } from "@ledgerfit/api-server/domains/triggers/handlers";
import type { TriggersDDDDependencies } from "@ledgerfit/api-server/domains/triggers";
import { createCreateFireRequest } from "@ledgerfit/factories/triggers";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { TRIGGERS_USE_CASES } from "../__factories__/use-cases.js";

describe("FireSmartContractTrigger", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: TriggersDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<TriggersDDDDependencies>(
      TRIGGERS_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 201 with created entity", async () => {
    const input = createCreateFireRequest();
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    mockRequest.body = input;
    vi.spyOn(mockDeps.executeFireSmartContractTrigger, "execute").mockResolvedValue(useCaseResult);

    await fireSmartContractTrigger(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeFireSmartContractTrigger.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
