/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { caseNoteRoutes } from "./case-note.routes.js";
export { hitRoutes } from "./hit.routes.js";
export { decideRoutes } from "./decide.routes.js";
export { revealRoutes } from "./reveal.routes.js";
