/**
 * Routes for Reveal
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createRevealRequest, getRevealRequest, listRevealRequests } from "../handlers/reveal.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function revealRoutes(fastify: FastifyInstance) {
  // POST /v1/investigation/reveals (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/investigation/reveals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInvestigationDependenciesForRequest();
        await createRevealRequest(request, reply, deps);
      });
    }
  );


  // GET /v1/investigation/reveals (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/investigation/reveals",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInvestigationDependenciesForRequest();
        await listRevealRequests(request, reply, deps);
      });
    }
  );


  // GET /v1/investigation/reveals/{revealRequestId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/investigation/reveals/:revealRequestId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { revealRequestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getInvestigationDependenciesForRequest();
        await getRevealRequest(request, reply, deps);
      });
    }
  );


}
