/**
 * Handlers for DataSourcePolicy
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { GovernanceDomainModule } from "../dependencies/governance-ddd.dependencies.js";
import type { CreateDataSourcePolicyInput, GetDataSourcePolicyInput, ListDataSourcePoliciesInput } from "@ledgerfit/services/governance";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/data-source-policies
 * Operation: listDataSourcePolicies
 */
export async function listDataSourcePolicies(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListDataSourcePoliciesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.dataSourcePolicies.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/data-source-policies
 * Operation: createDataSourcePolicy
 */
export async function createDataSourcePolicy(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateDataSourcePolicyInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.dataSourcePolicies.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/data-source-policies/{policyId}
 * Operation: getDataSourcePolicy
 */
export async function getDataSourcePolicy(
  request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: GovernanceDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetDataSourcePolicyInput = {
    policyId: request.params.policyId,
  };
  const result = await deps.useCases.dataSourcePolicies.get.execute(input);
  return reply.code(200).send(result);
}


