/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/training-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List training and scoring jobs */
        get: operations["listTrainingJobs"];
        put?: never;
        /** Create a ledger-window training or scoring job */
        post: operations["createTrainingJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        /** Get a training job by id */
        get: operations["getTrainingJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/training-jobs/{jobId}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel a queued or running job */
        post: operations["cancelTrainingJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 Problem Details (provisional mapping for gateway errors). */
        Problem: {
            /**
             * Format: uri
             * @description URI reference identifying the problem type.
             */
            type?: string;
            /** @description Short human-readable summary. */
            title?: string;
            /** @description HTTP status code. */
            status?: number;
            /** @description Human-readable explanation specific to this occurrence. */
            detail?: string;
            /**
             * Format: uri
             * @description URI reference identifying this occurrence.
             */
            instance?: string;
            /** @description Optional machine-readable error code from the gateway. */
            code?: string;
        } & {
            [key: string]: unknown;
        };
        JobId: string;
        /**
         * @description Server Layer (SMP/MPP batch) vs Streaming Layer
         * @enum {string}
         */
        ExecutionMode: "serverBatch" | "streaming";
        /** @enum {string} */
        LifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
        ArmThresholds: {
            /** @default 0.2 */
            minSupport: number;
            /** @default 0.7 */
            minConfidence: number;
            /** @default 3 */
            maxItems: number;
        };
        LedgerWindow: {
            ledgerId: string;
            fromBlock?: number;
            toBlock?: number;
            /** Format: date-time */
            fromTime?: string;
            /** Format: date-time */
            toTime?: string;
        };
        /** @enum {string} */
        JobStatus: "queued" | "running" | "succeeded" | "failed" | "cancelled";
        TrainingJob: {
            id: string;
            ledgerId: string;
            /**
             * @description Server Layer (SMP/MPP batch) vs Streaming Layer
             * @enum {string}
             */
            executionMode: "serverBatch" | "streaming";
            /** @enum {string} */
            lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
            /** @enum {string} */
            algorithm?: "associationRuleMining" | "riskScore" | "custom";
            armThresholds?: {
                /** @default 0.2 */
                minSupport: number;
                /** @default 0.7 */
                minConfidence: number;
                /** @default 3 */
                maxItems: number;
            };
            ledgerWindow?: {
                ledgerId: string;
                fromBlock?: number;
                toBlock?: number;
                /** Format: date-time */
                fromTime?: string;
                /** Format: date-time */
                toTime?: string;
            };
            triggerId?: string | null;
            thresholdPolicyId?: string | null;
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            artefactId?: string | null;
            errorDetail?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        TrainingJobListData: {
            items: {
                id: string;
                ledgerId: string;
                /**
                 * @description Server Layer (SMP/MPP batch) vs Streaming Layer
                 * @enum {string}
                 */
                executionMode: "serverBatch" | "streaming";
                /** @enum {string} */
                lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
                /** @enum {string} */
                algorithm?: "associationRuleMining" | "riskScore" | "custom";
                armThresholds?: {
                    /** @default 0.2 */
                    minSupport: number;
                    /** @default 0.7 */
                    minConfidence: number;
                    /** @default 3 */
                    maxItems: number;
                };
                ledgerWindow?: {
                    ledgerId: string;
                    fromBlock?: number;
                    toBlock?: number;
                    /** Format: date-time */
                    fromTime?: string;
                    /** Format: date-time */
                    toTime?: string;
                };
                triggerId?: string | null;
                thresholdPolicyId?: string | null;
                /** @enum {string} */
                status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
                artefactId?: string | null;
                errorDetail?: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                completedAt?: string | null;
            }[];
        };
        ResponseMeta: {
            /**
             * Format: uuid
             * @description Correlation id for this HTTP request.
             */
            requestId?: string;
            /** @description Optional end-to-end correlation id. */
            correlationId?: string;
            /**
             * Format: date-time
             * @description Server time when the payload was produced.
             */
            generatedAt?: string;
        };
        TrainingJobListResponse: {
            data: {
                items: {
                    id: string;
                    ledgerId: string;
                    /**
                     * @description Server Layer (SMP/MPP batch) vs Streaming Layer
                     * @enum {string}
                     */
                    executionMode: "serverBatch" | "streaming";
                    /** @enum {string} */
                    lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
                    /** @enum {string} */
                    algorithm?: "associationRuleMining" | "riskScore" | "custom";
                    armThresholds?: {
                        /** @default 0.2 */
                        minSupport: number;
                        /** @default 0.7 */
                        minConfidence: number;
                        /** @default 3 */
                        maxItems: number;
                    };
                    ledgerWindow?: {
                        ledgerId: string;
                        fromBlock?: number;
                        toBlock?: number;
                        /** Format: date-time */
                        fromTime?: string;
                        /** Format: date-time */
                        toTime?: string;
                    };
                    triggerId?: string | null;
                    thresholdPolicyId?: string | null;
                    /** @enum {string} */
                    status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
                    artefactId?: string | null;
                    errorDetail?: string | null;
                    /** Format: date-time */
                    createdAt: string;
                    /** Format: date-time */
                    completedAt?: string | null;
                }[];
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
        TrainingJobCreate: {
            ledgerId: string;
            /**
             * @description Server Layer (SMP/MPP batch) vs Streaming Layer
             * @enum {string}
             */
            executionMode: "serverBatch" | "streaming";
            /** @enum {string} */
            lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
            /** @enum {string} */
            algorithm: "associationRuleMining" | "riskScore" | "custom";
            armThresholds?: {
                /** @default 0.2 */
                minSupport: number;
                /** @default 0.7 */
                minConfidence: number;
                /** @default 3 */
                maxItems: number;
            };
            ledgerWindow?: {
                ledgerId: string;
                fromBlock?: number;
                toBlock?: number;
                /** Format: date-time */
                fromTime?: string;
                /** Format: date-time */
                toTime?: string;
            };
            triggerId?: string;
            thresholdPolicyId?: string;
        };
        TrainingJobResponse: {
            data: {
                id: string;
                ledgerId: string;
                /**
                 * @description Server Layer (SMP/MPP batch) vs Streaming Layer
                 * @enum {string}
                 */
                executionMode: "serverBatch" | "streaming";
                /** @enum {string} */
                lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
                /** @enum {string} */
                algorithm?: "associationRuleMining" | "riskScore" | "custom";
                armThresholds?: {
                    /** @default 0.2 */
                    minSupport: number;
                    /** @default 0.7 */
                    minConfidence: number;
                    /** @default 3 */
                    maxItems: number;
                };
                ledgerWindow?: {
                    ledgerId: string;
                    fromBlock?: number;
                    toBlock?: number;
                    /** Format: date-time */
                    fromTime?: string;
                    /** Format: date-time */
                    toTime?: string;
                };
                triggerId?: string | null;
                thresholdPolicyId?: string | null;
                /** @enum {string} */
                status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
                artefactId?: string | null;
                errorDetail?: string | null;
                /** Format: date-time */
                createdAt: string;
                /** Format: date-time */
                completedAt?: string | null;
            };
            meta?: {
                /**
                 * Format: uuid
                 * @description Correlation id for this HTTP request.
                 */
                requestId?: string;
                /** @description Optional end-to-end correlation id. */
                correlationId?: string;
                /**
                 * Format: date-time
                 * @description Server time when the payload was produced.
                 */
                generatedAt?: string;
            };
        };
    };
    responses: {
        /** @description Error (RFC 7807 Problem Details) */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Missing or invalid API key */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Malformed request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
                "application/json": {
                    /**
                     * Format: uri
                     * @description URI reference identifying the problem type.
                     */
                    type?: string;
                    /** @description Short human-readable summary. */
                    title?: string;
                    /** @description HTTP status code. */
                    status?: number;
                    /** @description Human-readable explanation specific to this occurrence. */
                    detail?: string;
                    /**
                     * Format: uri
                     * @description URI reference identifying this occurrence.
                     */
                    instance?: string;
                    /** @description Optional machine-readable error code from the gateway. */
                    code?: string;
                } & {
                    [key: string]: unknown;
                };
            };
        };
    };
    parameters: {
        /** @description Opaque keyset cursor for pagination. */
        Cursor: string;
        /** @description Page size. */
        Limit: number;
        /**
         * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
         *     Replay with the same key and body returns the original result; different
         *     body with the same key yields 409.
         */
        IdempotencyKey: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTrainingJobs: {
        parameters: {
            query?: {
                /** @description Opaque keyset cursor for pagination. */
                cursor?: string;
                /** @description Page size. */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Jobs page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            items: {
                                id: string;
                                ledgerId: string;
                                /**
                                 * @description Server Layer (SMP/MPP batch) vs Streaming Layer
                                 * @enum {string}
                                 */
                                executionMode: "serverBatch" | "streaming";
                                /** @enum {string} */
                                lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
                                /** @enum {string} */
                                algorithm?: "associationRuleMining" | "riskScore" | "custom";
                                armThresholds?: {
                                    /** @default 0.2 */
                                    minSupport: number;
                                    /** @default 0.7 */
                                    minConfidence: number;
                                    /** @default 3 */
                                    maxItems: number;
                                };
                                ledgerWindow?: {
                                    ledgerId: string;
                                    fromBlock?: number;
                                    toBlock?: number;
                                    /** Format: date-time */
                                    fromTime?: string;
                                    /** Format: date-time */
                                    toTime?: string;
                                };
                                triggerId?: string | null;
                                thresholdPolicyId?: string | null;
                                /** @enum {string} */
                                status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
                                artefactId?: string | null;
                                errorDetail?: string | null;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                completedAt?: string | null;
                            }[];
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    createTrainingJob: {
        parameters: {
            query?: never;
            header: {
                /**
                 * @description Client-supplied key for safe retries on mutating POSTs (≤128 chars).
                 *     Replay with the same key and body returns the original result; different
                 *     body with the same key yields 409.
                 */
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    ledgerId: string;
                    /**
                     * @description Server Layer (SMP/MPP batch) vs Streaming Layer
                     * @enum {string}
                     */
                    executionMode: "serverBatch" | "streaming";
                    /** @enum {string} */
                    lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
                    /** @enum {string} */
                    algorithm: "associationRuleMining" | "riskScore" | "custom";
                    armThresholds?: {
                        /** @default 0.2 */
                        minSupport: number;
                        /** @default 0.7 */
                        minConfidence: number;
                        /** @default 3 */
                        maxItems: number;
                    };
                    ledgerWindow?: {
                        ledgerId: string;
                        fromBlock?: number;
                        toBlock?: number;
                        /** Format: date-time */
                        fromTime?: string;
                        /** Format: date-time */
                        toTime?: string;
                    };
                    triggerId?: string;
                    thresholdPolicyId?: string;
                };
            };
        };
        responses: {
            /** @description Job created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            ledgerId: string;
                            /**
                             * @description Server Layer (SMP/MPP batch) vs Streaming Layer
                             * @enum {string}
                             */
                            executionMode: "serverBatch" | "streaming";
                            /** @enum {string} */
                            lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
                            /** @enum {string} */
                            algorithm?: "associationRuleMining" | "riskScore" | "custom";
                            armThresholds?: {
                                /** @default 0.2 */
                                minSupport: number;
                                /** @default 0.7 */
                                minConfidence: number;
                                /** @default 3 */
                                maxItems: number;
                            };
                            ledgerWindow?: {
                                ledgerId: string;
                                fromBlock?: number;
                                toBlock?: number;
                                /** Format: date-time */
                                fromTime?: string;
                                /** Format: date-time */
                                toTime?: string;
                            };
                            triggerId?: string | null;
                            thresholdPolicyId?: string | null;
                            /** @enum {string} */
                            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
                            artefactId?: string | null;
                            errorDetail?: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            completedAt?: string | null;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    getTrainingJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Training job */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            ledgerId: string;
                            /**
                             * @description Server Layer (SMP/MPP batch) vs Streaming Layer
                             * @enum {string}
                             */
                            executionMode: "serverBatch" | "streaming";
                            /** @enum {string} */
                            lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
                            /** @enum {string} */
                            algorithm?: "associationRuleMining" | "riskScore" | "custom";
                            armThresholds?: {
                                /** @default 0.2 */
                                minSupport: number;
                                /** @default 0.7 */
                                minConfidence: number;
                                /** @default 3 */
                                maxItems: number;
                            };
                            ledgerWindow?: {
                                ledgerId: string;
                                fromBlock?: number;
                                toBlock?: number;
                                /** Format: date-time */
                                fromTime?: string;
                                /** Format: date-time */
                                toTime?: string;
                            };
                            triggerId?: string | null;
                            thresholdPolicyId?: string | null;
                            /** @enum {string} */
                            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
                            artefactId?: string | null;
                            errorDetail?: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            completedAt?: string | null;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    cancelTrainingJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job cancelled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            id: string;
                            ledgerId: string;
                            /**
                             * @description Server Layer (SMP/MPP batch) vs Streaming Layer
                             * @enum {string}
                             */
                            executionMode: "serverBatch" | "streaming";
                            /** @enum {string} */
                            lifecycleStep: "modelInitialization" | "modelTraining" | "modelValidation" | "modelScoring" | "modelEvaluation" | "modelSerialization" | "modelCleanup";
                            /** @enum {string} */
                            algorithm?: "associationRuleMining" | "riskScore" | "custom";
                            armThresholds?: {
                                /** @default 0.2 */
                                minSupport: number;
                                /** @default 0.7 */
                                minConfidence: number;
                                /** @default 3 */
                                maxItems: number;
                            };
                            ledgerWindow?: {
                                ledgerId: string;
                                fromBlock?: number;
                                toBlock?: number;
                                /** Format: date-time */
                                fromTime?: string;
                                /** Format: date-time */
                                toTime?: string;
                            };
                            triggerId?: string | null;
                            thresholdPolicyId?: string | null;
                            /** @enum {string} */
                            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
                            artefactId?: string | null;
                            errorDetail?: string | null;
                            /** Format: date-time */
                            createdAt: string;
                            /** Format: date-time */
                            completedAt?: string | null;
                        };
                        meta?: {
                            /**
                             * Format: uuid
                             * @description Correlation id for this HTTP request.
                             */
                            requestId?: string;
                            /** @description Optional end-to-end correlation id. */
                            correlationId?: string;
                            /**
                             * Format: date-time
                             * @description Server time when the payload was produced.
                             */
                            generatedAt?: string;
                        };
                    };
                };
            };
            /** @description Malformed request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Error (RFC 7807 Problem Details) */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                    "application/json": {
                        /**
                         * Format: uri
                         * @description URI reference identifying the problem type.
                         */
                        type?: string;
                        /** @description Short human-readable summary. */
                        title?: string;
                        /** @description HTTP status code. */
                        status?: number;
                        /** @description Human-readable explanation specific to this occurrence. */
                        detail?: string;
                        /**
                         * Format: uri
                         * @description URI reference identifying this occurrence.
                         */
                        instance?: string;
                        /** @description Optional machine-readable error code from the gateway. */
                        code?: string;
                    } & {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
