/**
 * Routes for DataSourcePolicy
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyInstance, FastifyRequest, FastifyReply } from "fastify";
import { getDependencyContainer } from "../../../infrastructure/dependency-container.js";
import { createDataSourcePolicy, getDataSourcePolicy, listDataSourcePolicies } from "../handlers/data-source-policy.handlers.js";
import { wrapHandlerInExecutionContext } from "../../../lib/execution-context-wrapper.js";

// Fastify types are available globally
export async function dataSourcePolicyRoutes(fastify: FastifyInstance) {
  // POST /v1/data-source-policies (unscoped; scope set for security middleware)
  fastify.post(
    "/v1/data-source-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await createDataSourcePolicy(request, reply, deps);
      });
    }
  );


  // GET /v1/data-source-policies (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/data-source-policies",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: Record<string, string>; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await listDataSourcePolicies(request, reply, deps);
      });
    }
  );


  // GET /v1/data-source-policies/{policyId} (unscoped; scope set for security middleware)
  fastify.get(
    "/v1/data-source-policies/:policyId",
    { config: { scope: 'public' } },
    async (request: FastifyRequest<{ Params: { policyId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>, reply: FastifyReply) => {
      await wrapHandlerInExecutionContext(request, async () => {
        const deps = getDependencyContainer().getGovernanceDependenciesForRequest();
        await getDataSourcePolicy(request, reply, deps);
      });
    }
  );


}
