/**
 * GetDataSourcePolicy handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getDataSourcePolicy } from "@ledgerfit/api-server/domains/governance/handlers";
import type { GovernanceDDDDependencies } from "@ledgerfit/api-server/domains/governance";
import { createDataSourcePolicy as createDataSourcePolicyEntity } from "@ledgerfit/factories/governance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { GOVERNANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetDataSourcePolicy", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GovernanceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GovernanceDDDDependencies>(
      GOVERNANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = createDataSourcePolicyEntity({ orgId });
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetDataSourcePolicy, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { policyId: entity.id };

    await getDataSourcePolicy(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetDataSourcePolicy.execute).toHaveBeenCalledWith(expect.objectContaining({ policyId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { policyId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetDataSourcePolicy, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getDataSourcePolicy(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
