/**
 * ListDataSourcePolicies handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { listDataSourcePolicies } from "@ledgerfit/api-server/domains/governance/handlers";
import type { GovernanceDDDDependencies } from "@ledgerfit/api-server/domains/governance";
import { createDataSourcePolicy as createDataSourcePolicyEntity } from "@ledgerfit/factories/governance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { GOVERNANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("ListDataSourcePolicies", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: GovernanceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<GovernanceDDDDependencies>(
      GOVERNANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with list of entities", async () => {
    const entities = [
      createDataSourcePolicyEntity({ orgId }),
      createDataSourcePolicyEntity({ orgId }),
    ];
    const useCaseResult = {
      data: { items: entities, nextCursor: undefined, prevCursor: undefined },
      meta: { correlationId: "test", timestamp: new Date().toISOString(), pagination: {} }
    };
    
    vi.spyOn(mockDeps.executeListDataSourcePolicies, "execute").mockResolvedValue(useCaseResult);

    await listDataSourcePolicies(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeListDataSourcePolicies.execute).toHaveBeenCalledWith(expect.anything());
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

});
