/**
 * Handlers for CaseNote
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InvestigationDomainModule } from "../dependencies/investigation-ddd.dependencies.js";
import type { CreateCaseNoteInput, ListCaseNotesInput } from "@ledgerfit/services/investigation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/investigation/case-notes
 * Operation: listCaseNotes
 */
export async function listCaseNotes(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: InvestigationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListCaseNotesInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.caseNotes.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/investigation/case-notes
 * Operation: createCaseNote
 */
export async function createCaseNote(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: InvestigationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateCaseNoteInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.caseNotes.create.execute(input);
  return reply.code(201).send(result);
}


