/**
 * Handlers for Decide
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InvestigationDomainModule } from "../dependencies/investigation-ddd.dependencies.js";
import type { DecideRevealRequestInput } from "@ledgerfit/services/investigation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for POST /v1/investigation/reveals/{revealRequestId}/decide
 * Operation: decideRevealRequest
 */
export async function decideRevealRequest(
  request: FastifyRequest<{ Params: { revealRequestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: InvestigationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: DecideRevealRequestInput = {
    revealRequestId: request.params.revealRequestId,
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.decides.get.execute(input);
  return reply.code(200).send(result);
}


