/**
 * Handlers for Hit
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InvestigationDomainModule } from "../dependencies/investigation-ddd.dependencies.js";
import type { ListMaskedHitsInput } from "@ledgerfit/services/investigation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/investigation/hits
 * Operation: listMaskedHits
 */
export async function listMaskedHits(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: InvestigationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListMaskedHitsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.hits.list.execute(input);
  return reply.code(200).send(result);
}


