/**
 * Handlers index
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export * from "./case-note.handlers.js";
export * from "./decide.handlers.js";
export * from "./hit.handlers.js";
export * from "./reveal.handlers.js";
