/**
 * Handlers for Reveal
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { InvestigationDomainModule } from "../dependencies/investigation-ddd.dependencies.js";
import type { CreateRevealRequestInput, GetRevealRequestInput, ListRevealRequestsInput } from "@ledgerfit/services/investigation";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/investigation/reveals
 * Operation: listRevealRequests
 */
export async function listRevealRequests(
  request: FastifyRequest<{ Params: Record<string, string>; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: InvestigationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListRevealRequestsInput = {
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.reveals.list.execute(input);
  return reply.code(200).send(result);
}


/**
 * Handler for POST /v1/investigation/reveals
 * Operation: createRevealRequest
 */
export async function createRevealRequest(
  request: FastifyRequest,
  reply: FastifyReply,
  deps: InvestigationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: CreateRevealRequestInput = {
    ...(request.body ?? {}),
  };
  const result = await deps.useCases.reveals.create.execute(input);
  return reply.code(201).send(result);
}


/**
 * Handler for GET /v1/investigation/reveals/{revealRequestId}
 * Operation: getRevealRequest
 */
export async function getRevealRequest(
  request: FastifyRequest<{ Params: { revealRequestId: string }; Querystring: Record<string, string | string[] | undefined>; Body: unknown }>,
  reply: FastifyReply,
  deps: InvestigationDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: GetRevealRequestInput = {
    revealRequestId: request.params.revealRequestId,
  };
  const result = await deps.useCases.reveals.get.execute(input);
  return reply.code(200).send(result);
}


