/**
 * Routes index
 *
 * Generated by Routes Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

export { modelArtefactRoutes } from "./model-artefact.routes.js";
export { promoteRoutes } from "./promote.routes.js";
export { ruleRoutes } from "./rule.routes.js";
