/**
 * Ledgers DDD Dependencies - Composition root
 *
 * Generated by Dependencies Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * Ledgers Domain Module - Composition root
 *
 * DDD: Composition root for ledgers domain. Exposes repos (ports) and use cases
 * grouped by aggregate. No orgId at build time — use execution context at call time.
 */

import {
  AcknowledgeRepositoryAdapter,
  EventRepositoryAdapter,
  FreezeOrderRepositoryAdapter,
  FreezeRepositoryAdapter,
  LedgerRepositoryAdapter,
  MemberRepositoryAdapter,
  ReleaseRepositoryAdapter,
} from "@ledgerfit/adapters/ledgers";
import { getIdGeneratorService } from "@ledgerfit/adapters";
import type { AdapterDynamoDBClient } from "@ledgerfit/adapters";
import { executionContextService } from "../../../lib/execution-context.service.js";
// Use-case constructors (concrete)
import {
  ExecuteAcknowledgeFreezeOrder,
  ExecuteAddPharmacyMember,
  ExecuteAnchorPrescriptionEvent,
  ExecuteFreezePharmacyMember,
  ExecuteGetLedger,
  ExecuteListFreezeOrders,
  ExecuteListLedgers,
  ExecuteListPharmacyMembers,
  ExecuteListPrescriptionEventRefs,
  ExecuteRegisterLedger,
  ExecuteReleaseFreezeOrder,
} from "@ledgerfit/services/ledgers/usecases";
// Ports (interfaces)
import type {
  AcknowledgeRepository,
  EventRepository,
  FreezeOrderRepository,
  FreezeRepository,
  LedgerRepository,
  MemberRepository,
  ReleaseRepository,
} from "@ledgerfit/services/ledgers/ports";

export interface LedgersDomainModule {
  repos: {
    acknowledges: AcknowledgeRepository;
    events: EventRepository;
    freezeOrders: FreezeOrderRepository;
    freezes: FreezeRepository;
    ledgers: LedgerRepository;
    members: MemberRepository;
    releases: ReleaseRepository;
  };
  useCases: {
    acknowledges: {
      get: ExecuteAcknowledgeFreezeOrder;
    };
    events: {
      get: ExecuteAnchorPrescriptionEvent;
      list: ExecuteListPrescriptionEventRefs;
    };
    freezeOrders: {
      list: ExecuteListFreezeOrders;
    };
    freezes: {
      get: ExecuteFreezePharmacyMember;
    };
    ledgers: {
      create: ExecuteRegisterLedger;
      get: ExecuteGetLedger;
      list: ExecuteListLedgers;
    };
    members: {
      create: ExecuteAddPharmacyMember;
      list: ExecuteListPharmacyMembers;
    };
    releases: {
      get: ExecuteReleaseFreezeOrder;
    };
  };
}

export function buildLedgersDomainModule(
  dynamoClient: AdapterDynamoDBClient,
): LedgersDomainModule {
  // Adapters implementing ports (adapters encapsulate Ddb)
  const repos = (() => {
    const obj: {
      acknowledges?: AcknowledgeRepository;
      events?: EventRepository;
      freezeOrders?: FreezeOrderRepository;
      freezes?: FreezeRepository;
      ledgers?: LedgerRepository;
      members?: MemberRepository;
      releases?: ReleaseRepository;
    } = {};

    obj.acknowledges = new AcknowledgeRepositoryAdapter(dynamoClient);
    obj.events = new EventRepositoryAdapter(dynamoClient);
    obj.freezeOrders = new FreezeOrderRepositoryAdapter(dynamoClient);
    obj.freezes = new FreezeRepositoryAdapter(dynamoClient);
    obj.ledgers = new LedgerRepositoryAdapter(dynamoClient);
    obj.members = new MemberRepositoryAdapter(dynamoClient);
    obj.releases = new ReleaseRepositoryAdapter(dynamoClient);
    return {
      acknowledges: obj.acknowledges!,
      events: obj.events!,
      freezeOrders: obj.freezeOrders!,
      freezes: obj.freezes!,
      ledgers: obj.ledgers!,
      members: obj.members!,
      releases: obj.releases!,
    };
  })();

  const executionContext = executionContextService;
  const idGenerator = getIdGeneratorService();

  // Use cases depend only on ports (repos.*)
  const useCases = {
    acknowledges: {
      get: new ExecuteAcknowledgeFreezeOrder(executionContext, idGenerator, repos.acknowledges),
    },
    events: {
      get: new ExecuteAnchorPrescriptionEvent(executionContext, idGenerator, repos.events),
      list: new ExecuteListPrescriptionEventRefs(executionContext, idGenerator, repos.events),
    },
    freezeOrders: {
      list: new ExecuteListFreezeOrders(executionContext, idGenerator, repos.freezeOrders),
    },
    freezes: {
      get: new ExecuteFreezePharmacyMember(executionContext, idGenerator, repos.freezes),
    },
    ledgers: {
      create: new ExecuteRegisterLedger(executionContext, idGenerator, repos.ledgers),
      get: new ExecuteGetLedger(executionContext, idGenerator, repos.ledgers),
      list: new ExecuteListLedgers(executionContext, idGenerator, repos.ledgers),
    },
    members: {
      create: new ExecuteAddPharmacyMember(executionContext, idGenerator, repos.members),
      list: new ExecuteListPharmacyMembers(executionContext, idGenerator, repos.members),
    },
    releases: {
      get: new ExecuteReleaseFreezeOrder(executionContext, idGenerator, repos.releases),
    },
  };
  return { repos, useCases: useCases as LedgersDomainModule["useCases"] };
}
