/**
 * GetProvenanceRecord handler tests
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: provenance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { describe, it, expect, beforeEach, vi } from "vitest";
import { getProvenanceRecord } from "@ledgerfit/api-server/domains/provenance/handlers";
import type { ProvenanceDDDDependencies } from "@ledgerfit/api-server/domains/provenance";
import { createMockRequest, createMockReply, createMockDependencies, TEST_ORG_ID } from "@ledgerfit/tests/shared";
import { PROVENANCE_USE_CASES } from "../__factories__/use-cases.js";

describe("GetProvenanceRecord", () => {
  let mockRequest: ReturnType<typeof createMockRequest>;
  let mockReply: ReturnType<typeof createMockReply>;
  let mockDeps: ProvenanceDDDDependencies;
  const orgId = TEST_ORG_ID;

  beforeEach(() => {
    mockRequest = createMockRequest({ orgId });
    mockReply = createMockReply();
    mockDeps = createMockDependencies<ProvenanceDDDDependencies>(
      PROVENANCE_USE_CASES,
      {
        // Mock use case dependencies here
      }
    );
  });

  it("should return 200 with entity when found", async () => {
    const entity = { id: 'mock-id', orgId } as any;
    const useCaseResult = { data: entity, meta: { correlationId: "test", timestamp: new Date().toISOString() } };
    
    vi.spyOn(mockDeps.executeGetProvenanceRecord, "execute").mockResolvedValue(useCaseResult);
    mockRequest.params = { recordId: entity.id };

    await getProvenanceRecord(mockRequest, mockReply, mockDeps);

    expect(mockDeps.executeGetProvenanceRecord.execute).toHaveBeenCalledWith(expect.objectContaining({ recordId: entity.id }));
    expect(mockReply.code).toHaveBeenCalledWith(200);
    expect(mockReply.send).toHaveBeenCalledWith(useCaseResult);
  });

  it("should return error when entity not found", async () => {
    const nonExistentId = "non-existent-id";
    mockRequest.params = { recordId: nonExistentId };
    
    vi.spyOn(mockDeps.executeGetProvenanceRecord, "execute").mockRejectedValue(
      new Error("Entity not found")
    );

    await expect(
      getProvenanceRecord(mockRequest, mockReply, mockDeps)
    ).rejects.toThrow();
  });

});
