/**
 * Use Case List
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: training
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


/**
 * Training Domain Use Cases
 * 
 * List of all use case names for the training domain.
 * Used by createMockDependencies() to pre-create mocks.
 */

export const TRAINING_USE_CASES = [
  "executeCancelTrainingJob",
  "executeCreateTrainingJob",
  "executeGetTrainingJob",
  "executeListTrainingJobs"
] as const;
