/**
 * FreezeOrder Entity Factory
 *
 * Generated by Test Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */


import { faker } from "@faker-js/faker";
import type { FreezeOrderEntity } from "@ledgerfit/core/ledgers/models/index.js";
import { ledgersSchemas } from "@ledgerfit/core/ledgers";
import { ulid } from "ulid";

// Domain prefix from OpenAPI spec info.x-domain
const DOMAIN_PREFIX = "ldg";

export function createFreezeOrder(overrides: Partial<FreezeOrderEntity> = {}) {
  const raw = {
    id: overrides.id ?? `${DOMAIN_PREFIX}_${ulid().toLowerCase()}`,
    createdAt: overrides.createdAt ?? new Date().toISOString(),
    updatedAt: overrides.updatedAt ?? new Date().toISOString(),
    issuedAt: overrides.issuedAt ?? new Date().toISOString(),
    ledgerId: overrides.ledgerId ?? faker.string.uuid(),
    memberId: overrides.memberId ?? faker.string.uuid(),
    reason: overrides.reason ?? faker.lorem.word(),
    slaDeadline: overrides.slaDeadline ?? new Date().toISOString(),
    status: overrides.status ?? "active",
    ...overrides,
  };

  return ledgersSchemas.FreezeOrder.parse(raw);
}

export function freezeOrderBatch(n = 3, overrides = {}) {
  return Array.from({ length: n }, () => createFreezeOrder(overrides));
}
