/**
 * ExecuteCreateSmartContractTrigger - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteCreateSmartContractTrigger Use Case
 *
 * DDD: Application use case for create SmartContractTrigger.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { CreateSmartContractTriggerInput, CreateSmartContractTriggerOutput } from "../dto/smart-contract-trigger.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { SmartContractTriggerRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteCreateSmartContractTrigger {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly smartContractTrigger: SmartContractTriggerRepository
  ) {}

  async execute(input: CreateSmartContractTriggerInput): Promise<CreateSmartContractTriggerOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trgId();

    // All field names extracted from OpenAPI spec: algorithm, armThresholds, condition, cronExpression, enabled, executionMode, ledgerId, lifecycleStep, name, newBlocksThreshold
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.executionMode) {
      throw new ValidationError("executionMode is required");
    }
    if (!input.condition) {
      throw new ValidationError("condition is required");
    }
    if (!input.ledgerId) {
      throw new ValidationError("ledgerId is required");
    }
    if (!input.algorithm) {
      throw new ValidationError("algorithm is required");
    }
    if (!input.lifecycleStep) {
      throw new ValidationError("lifecycleStep is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (triggers domain)
    const entityId = this.idGenerator.trgId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.smartContractTrigger.createSmartContractTrigger({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as CreateSmartContractTriggerOutput;
  }
}
