/**
 * ExecuteFireSmartContractTrigger - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: triggers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteFireSmartContractTrigger Use Case
 *
 * DDD: Application use case for get Fire.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { FireSmartContractTriggerInput, FireSmartContractTriggerOutput } from "../dto/fire.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { FireRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteFireSmartContractTrigger {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly fire: FireRepository
  ) {}

  async execute(input: FireSmartContractTriggerInput): Promise<FireSmartContractTriggerOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.trgId();

    // All field names extracted from OpenAPI spec: none
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).triggerId) {
      throw new ValidationError("triggerId is required");
    }
    const triggerId = (input as any).triggerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.fire.fireSmartContractTrigger({ triggerId: triggerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${triggerId}`);
    }

    return entity as FireSmartContractTriggerOutput;
  }
}
