/**
 * ExecuteListPharmacyMembers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListPharmacyMembers Use Case
 *
 * DDD: Application use case for list Member.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListPharmacyMembersInput, ListPharmacyMembersOutput } from "../dto/member.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { MemberRepository } from "../ports";

export class ExecuteListPharmacyMembers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly member: MemberRepository
  ) {}

  async execute(input: ListPharmacyMembersInput): Promise<ListPharmacyMembersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ldgId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.member.listPharmacyMembers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListPharmacyMembersOutput;
  }
}
