/**
 * ExecuteListLedgers - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteListLedgers Use Case
 *
 * DDD: Application use case for list Ledger.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { ListLedgersInput, ListLedgersOutput } from "../dto/ledger.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { LedgerRepository } from "../ports";

export class ExecuteListLedgers {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ledger: LedgerRepository
  ) {}

  async execute(input: ListLedgersInput): Promise<ListLedgersOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ldgId();

    // All field names extracted from OpenAPI spec: none
    // List entities via repository
    const result = await this.ledger.listLedgers({ ...input, orgId: this.context.getOrgId(), correlationId } as any);

    return result as ListLedgersOutput;
  }
}
