/**
 * ExecuteFreezePharmacyMember - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteFreezePharmacyMember Use Case
 *
 * DDD: Application use case for get Freeze.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { FreezePharmacyMemberInput, FreezePharmacyMemberOutput } from "../dto/freeze.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { FreezeRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteFreezePharmacyMember {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly freeze: FreezeRepository
  ) {}

  async execute(input: FreezePharmacyMemberInput): Promise<FreezePharmacyMemberOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ldgId();

    // All field names extracted from OpenAPI spec: freezeAnchoring, freezeScoring, reason, slaHours
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).memberId) {
      throw new ValidationError("memberId is required");
    }
    const memberId = (input as any).memberId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.freeze.freezePharmacyMember({ memberId: memberId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${memberId}`);
    }

    return entity as FreezePharmacyMemberOutput;
  }
}
