/**
 * ExecuteRegisterLedger - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteRegisterLedger Use Case
 *
 * DDD: Application use case for create Ledger.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { RegisterLedgerInput, RegisterLedgerOutput } from "../dto/ledger.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { LedgerRepository } from "../ports";
import { PermissionDeniedError, ValidationError } from "../errors";
import { CanCreate } from "../policies/can-create.policy";
export class ExecuteRegisterLedger {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly ledger: LedgerRepository
  ) {}

  async execute(input: RegisterLedgerInput): Promise<RegisterLedgerOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ldgId();

    // All field names extracted from OpenAPI spec: consensusHint, endpointRef, fabricType, name
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!input.fabricType) {
      throw new ValidationError("fabricType is required");
    }
    if (!input.name) {
      throw new ValidationError("name is required");
    }    // Check policy
    if (!CanCreate.allow({} as any, "")) {
      throw new PermissionDeniedError("Operation not allowed");
    }

    // Generate entity ID in services layer using IdGeneratorService (ledgers domain)
    const entityId = this.idGenerator.ldgId();

    // Create entity via repository (pass ID and correlation ID for response meta)
    const entity = await this.ledger.registerLedger({ ...input, id: entityId, createdByActorId: (input as any).createdByActorId ?? this.context.getUserId(), createdByActorType: (input as any).createdByActorType ?? "human", orgId: this.context.getOrgId(), correlationId } as any);

    return entity as RegisterLedgerOutput;
  }
}
