/**
 * ExecuteAnchorPrescriptionEvent - Application use case
 *
 * Generated by Use Case Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: ledgers
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ExecuteAnchorPrescriptionEvent Use Case
 *
 * DDD: Application use case for get Event.
 * Orchestrates the business flow using ports (interfaces).
 */

import type { AnchorPrescriptionEventInput, AnchorPrescriptionEventOutput } from "../dto/event.dto";
import type { ExecutionContextService, IdGeneratorService } from "@ledgerfit/services/_shared/index.js";
import type { EventRepository } from "../ports";
import { NotFoundError, ValidationError } from "../errors";

export class ExecuteAnchorPrescriptionEvent {
  constructor(
    private readonly context: ExecutionContextService,
    private readonly idGenerator: IdGeneratorService,
    private readonly event: EventRepository
  ) {}

  async execute(input: AnchorPrescriptionEventInput): Promise<AnchorPrescriptionEventOutput> {
    // Generate correlation ID for this request (domain-prefixed format: {domain_prefix}_{ulid})
    const correlationId = this.idGenerator.ldgId();

    // All field names extracted from OpenAPI spec: contentHash, drugClassHints, occurredAt, pharmacyMemberId
    // Validate input
    if (!input) {
      throw new ValidationError("Input is required");
    }
    if (!(input as any).ledgerId) {
      throw new ValidationError("ledgerId is required");
    }
    const ledgerId = (input as any).ledgerId;

    // Load entity via repository (pass correlation ID for response meta)
    const entity = await this.event.anchorPrescriptionEvent({ ledgerId: ledgerId, orgId: this.context.getOrgId(), correlationId } as any);
    if (!entity) {
      throw new NotFoundError(`Entity not found: ${ledgerId}`);
    }

    return entity as AnchorPrescriptionEventOutput;
  }
}
