/**
 * CaseNote Entity - Domain model
 *
 * Generated by Entity Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: investigation
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { components } from "../openapi/investigation.openapi.types.js";
import { schemas } from "../schemas/investigation.schemas.js";

/**
 * Entity: CaseNoteEntity
 * Description: Represents the CaseNote domain model.
 * Source: schemas.CaseNote
 * Type: Domain Entity (API)
 */
export const CaseNoteEntitySchema = schemas.CaseNote;
export type CaseNoteEntity = components["schemas"]["CaseNote"];
