/**
 * DataSourcePolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * DataSourcePolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements DataSourcePolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  DataSourcePolicyRepository,
} from "@ledgerfit/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { DataSourcePolicyRepositoryDdb } from "./data-source-policy-repository.ddb.js";

/**
 * DataSourcePolicyRepositoryAdapter
 *
 * Implements DataSourcePolicyRepository port for infrastructure layer.
 */
export class DataSourcePolicyRepositoryAdapter implements DataSourcePolicyRepository {
  private readonly ddb: DataSourcePolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new DataSourcePolicyRepositoryDdb(this.dynamoClient);
  }

  async listDataSourcePolicies(input: Parameters<DataSourcePolicyRepository['listDataSourcePolicies']>[0]): Promise<Awaited<ReturnType<DataSourcePolicyRepository['listDataSourcePolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listDataSourcePolicies(input);
  }

  async createDataSourcePolicy(input: Parameters<DataSourcePolicyRepository['createDataSourcePolicy']>[0]): Promise<Awaited<ReturnType<DataSourcePolicyRepository['createDataSourcePolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createDataSourcePolicy(input);
  }

  async getDataSourcePolicy(input: Parameters<DataSourcePolicyRepository['getDataSourcePolicy']>[0]): Promise<Awaited<ReturnType<DataSourcePolicyRepository['getDataSourcePolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getDataSourcePolicy(input);
  }
}
