/**
 * ThresholdPolicyRepositoryAdapter - Port Adapter Implementation
 *
 * Generated by Port Adapter Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: governance
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

/**
 * ThresholdPolicyRepositoryAdapter
 *
 * DDD: Infrastructure adapter that implements ThresholdPolicyRepository port.
 * Handles infrastructure concerns (HTTP, database, external APIs).
 * Encapsulates Ddb creation - api-server passes dynamoClient only.
 */

import type {
  ThresholdPolicyRepository,
} from "@ledgerfit/services/governance";
import type { AdapterDynamoDBClient } from "../_shared/dynamodb-client-types.js";
import { ThresholdPolicyRepositoryDdb } from "./threshold-policy-repository.ddb.js";

/**
 * ThresholdPolicyRepositoryAdapter
 *
 * Implements ThresholdPolicyRepository port for infrastructure layer.
 */
export class ThresholdPolicyRepositoryAdapter implements ThresholdPolicyRepository {
  private readonly ddb: ThresholdPolicyRepositoryDdb;

  constructor(
    private readonly dynamoClient: AdapterDynamoDBClient
  ) {
    this.ddb = new ThresholdPolicyRepositoryDdb(this.dynamoClient);
  }

  async listThresholdPolicies(input: Parameters<ThresholdPolicyRepository['listThresholdPolicies']>[0]): Promise<Awaited<ReturnType<ThresholdPolicyRepository['listThresholdPolicies']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.listThresholdPolicies(input);
  }

  async createThresholdPolicy(input: Parameters<ThresholdPolicyRepository['createThresholdPolicy']>[0]): Promise<Awaited<ReturnType<ThresholdPolicyRepository['createThresholdPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.createThresholdPolicy(input);
  }

  async getThresholdPolicy(input: Parameters<ThresholdPolicyRepository['getThresholdPolicy']>[0]): Promise<Awaited<ReturnType<ThresholdPolicyRepository['getThresholdPolicy']>>> {
    // Delegate to DynamoDB repository
    return await this.ddb.getThresholdPolicy(input);
  }
}
