/**
 * Handlers for Rule
 *
 * Generated by Handler Generator v2.0.0
 * Generator Version: 2.0.0
 * Domain: models
 *
 * ⚠️  DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated. Any manual changes will be overwritten.
 */

import type { FastifyRequest, FastifyReply } from "fastify";
import type { ModelsDomainModule } from "../dependencies/models-ddd.dependencies.js";
import type { ListAssociationRulesInput } from "@ledgerfit/services/models";
// Use cases are available via deps.useCases.<repoKey>.<verb>
// Execution context is automatically set up by route wrapper (wrapHandlerInExecutionContext)

/**
 * Handler for GET /v1/model-artefacts/{artefactId}/rules
 * Operation: listAssociationRules
 */
export async function listAssociationRules(
  request: FastifyRequest<{ Params: { artefactId: string }; Querystring: { cursor?: string | string[], limit?: string | string[] }; Body: unknown }>,
  reply: FastifyReply,
  deps: ModelsDomainModule
): Promise<void> {
  // Security: orgId validated by setOrgContext hook; use case gets it from execution context
  const input: ListAssociationRulesInput = {
    artefactId: request.params.artefactId,
    ...(request.query ?? {}),
  };
  const result = await deps.useCases.rules.list.execute(input);
  return reply.code(200).send(result);
}


